/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

/**
 *
 * @author Rafael
 */
public class JPActivateProperty extends javax.swing.JPanel {

    /**
     * Creates new form JPActivateProperty
     */
    public JPActivateProperty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activatePropertyPanel = new javax.swing.JPanel();
        activatePropertyTopBarPanel = new javax.swing.JPanel();
        activatePropertyLanguageBox = new javax.swing.JComboBox<>();
        activatePropertyNameLabel = new javax.swing.JLabel();
        activatePropertyMessageButton = new javax.swing.JButton();
        activatePropertyLogoPanel = new javax.swing.JPanel();
        activatePropertyInfoPanel = new javax.swing.JPanel();
        activatePropertyInfoInfoPanel = new javax.swing.JPanel();
        activatePropertyPhotoField = new javax.swing.JTextField();
        activatePropertyDescription = new javax.swing.JTextField();
        activatePropertyLocation = new javax.swing.JTextField();
        activatePropertyType = new javax.swing.JComboBox<>();
        activatePropertyDivisions = new javax.swing.JComboBox<>();
        activatePropertyDiscountLabel = new javax.swing.JLabel();
        activatePropertyDicountTextField = new javax.swing.JTextField();
        activatePropertyPercentageLabel = new javax.swing.JLabel();
        activatePropertyAvailableDatePicker = new org.jdesktop.swingx.JXDatePicker();
        activatePropertyPrice = new javax.swing.JTextField();
        activatePropertyCoinType = new javax.swing.JLabel();
        activatePropertyScore = new java.awt.Label();
        activatePropertyPontuationLabel = new javax.swing.JLabel();
        activatePropertyScrollPane = new javax.swing.JScrollPane();
        activatePropertyRating = new javax.swing.JList<>();
        activatePropertyCharacteristicsPanel = new javax.swing.JPanel();
        activatePropertyContainerPanel = new javax.swing.JPanel();
        activatePropertyMinClientsField = new javax.swing.JTextField();
        activatePropertyMaxClientsField = new javax.swing.JTextField();
        activatePropertyMinClientsLabel = new javax.swing.JLabel();
        activatePropertyMaxClientsLabel = new javax.swing.JLabel();
        activatePropertyNRoomsField = new javax.swing.JTextField();
        activatePropertyNBathroomsField = new javax.swing.JTextField();
        activatePropertyNRoomsLabel = new javax.swing.JLabel();
        activatePropertyNBathroomsLabel = new javax.swing.JLabel();
        activatePropertyNBedsField = new javax.swing.JTextField();
        activatePropertyBedsTypeBox = new javax.swing.JComboBox();
        activatePropertyNBedsLabel = new javax.swing.JLabel();
        activatePropertyExtrasLeftPanel = new javax.swing.JPanel();
        activatePropertyPetsCheckBox = new javax.swing.JCheckBox();
        activatePropertyBreakfastCheckBox = new javax.swing.JCheckBox();
        activatePropertyWifiCheckBox = new javax.swing.JCheckBox();
        activatePropertyPoolCheckBox = new javax.swing.JCheckBox();
        activatePropertyWashingMachineCheckBox = new javax.swing.JCheckBox();
        activatePropertyKitchenCheckBox = new javax.swing.JCheckBox();
        activatePropertyActivateButton = new javax.swing.JButton();
        activatePropertyCancelButton = new javax.swing.JButton();
        activatePropertyErrorPanel = new javax.swing.JPanel();

        activatePropertyLanguageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT", "EN" }));

        activatePropertyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        activatePropertyNameLabel.setText("Rafael Morais");

        activatePropertyMessageButton.setText("jButton7");
        activatePropertyMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activatePropertyMessageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout activatePropertyTopBarPanelLayout = new javax.swing.GroupLayout(activatePropertyTopBarPanel);
        activatePropertyTopBarPanel.setLayout(activatePropertyTopBarPanelLayout);
        activatePropertyTopBarPanelLayout.setHorizontalGroup(
            activatePropertyTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activatePropertyLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(activatePropertyMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(activatePropertyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        activatePropertyTopBarPanelLayout.setVerticalGroup(
            activatePropertyTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyTopBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(activatePropertyTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activatePropertyTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(activatePropertyNameLabel)
                        .addComponent(activatePropertyMessageButton))
                    .addComponent(activatePropertyLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout activatePropertyLogoPanelLayout = new javax.swing.GroupLayout(activatePropertyLogoPanel);
        activatePropertyLogoPanel.setLayout(activatePropertyLogoPanelLayout);
        activatePropertyLogoPanelLayout.setHorizontalGroup(
            activatePropertyLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        activatePropertyLogoPanelLayout.setVerticalGroup(
            activatePropertyLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        activatePropertyPhotoField.setText("jTextField1");

        activatePropertyDescription.setText("jTextField2");

        activatePropertyLocation.setText("ola");

        activatePropertyType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa" }));

        activatePropertyDivisions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1", "T2", "T3", "T4", "T5" }));

        activatePropertyDiscountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        activatePropertyDiscountLabel.setText("Desconto:");

        activatePropertyDicountTextField.setText("jTextField4");

        activatePropertyPercentageLabel.setText("%");

        activatePropertyPrice.setText("jTextField5");

        activatePropertyCoinType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        activatePropertyCoinType.setText("€");

        activatePropertyScore.setAlignment(java.awt.Label.CENTER);
        activatePropertyScore.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        activatePropertyScore.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        activatePropertyScore.setText("8.7");

        activatePropertyPontuationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        activatePropertyPontuationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activatePropertyPontuationLabel.setText("PONTUAÇÃO");

        activatePropertyRating.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        activatePropertyScrollPane.setViewportView(activatePropertyRating);

        activatePropertyContainerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Características"));

        activatePropertyMinClientsField.setEditable(false);
        activatePropertyMinClientsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activatePropertyMinClientsField.setText("1");

        activatePropertyMaxClientsField.setEditable(false);
        activatePropertyMaxClientsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activatePropertyMaxClientsField.setText("5");

        activatePropertyMinClientsLabel.setText("Nº Viajantes Mínimo");

        activatePropertyMaxClientsLabel.setText("Nº Viajantes Máximo");

        activatePropertyNRoomsField.setEditable(false);
        activatePropertyNRoomsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activatePropertyNRoomsField.setText("3");

        activatePropertyNBathroomsField.setEditable(false);
        activatePropertyNBathroomsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activatePropertyNBathroomsField.setText("7");

        activatePropertyNRoomsLabel.setText("Nº Quartos");

        activatePropertyNBathroomsLabel.setText("Nº Quartos de Banho");

        activatePropertyNBedsField.setEditable(false);
        activatePropertyNBedsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activatePropertyNBedsField.setText("5");

        activatePropertyBedsTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipos de Cama" }));

        activatePropertyNBedsLabel.setText("Nº Camas");

        activatePropertyPetsCheckBox.setText("Animais de Estimação");
        activatePropertyPetsCheckBox.setEnabled(false);

        activatePropertyBreakfastCheckBox.setSelected(true);
        activatePropertyBreakfastCheckBox.setText("Pequeno Almoço");
        activatePropertyBreakfastCheckBox.setEnabled(false);

        activatePropertyWifiCheckBox.setText("Wi-fi");
        activatePropertyWifiCheckBox.setEnabled(false);

        javax.swing.GroupLayout activatePropertyExtrasLeftPanelLayout = new javax.swing.GroupLayout(activatePropertyExtrasLeftPanel);
        activatePropertyExtrasLeftPanel.setLayout(activatePropertyExtrasLeftPanelLayout);
        activatePropertyExtrasLeftPanelLayout.setHorizontalGroup(
            activatePropertyExtrasLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyExtrasLeftPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(activatePropertyExtrasLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activatePropertyPetsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activatePropertyBreakfastCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activatePropertyWifiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        activatePropertyExtrasLeftPanelLayout.setVerticalGroup(
            activatePropertyExtrasLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyExtrasLeftPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(activatePropertyPetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activatePropertyBreakfastCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activatePropertyWifiCheckBox)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        activatePropertyPoolCheckBox.setSelected(true);
        activatePropertyPoolCheckBox.setText("Piscina");
        activatePropertyPoolCheckBox.setEnabled(false);

        activatePropertyWashingMachineCheckBox.setText("Máquinha de Lavar");
        activatePropertyWashingMachineCheckBox.setEnabled(false);

        activatePropertyKitchenCheckBox.setText("Cozinha");
        activatePropertyKitchenCheckBox.setEnabled(false);

        javax.swing.GroupLayout activatePropertyContainerPanelLayout = new javax.swing.GroupLayout(activatePropertyContainerPanel);
        activatePropertyContainerPanel.setLayout(activatePropertyContainerPanelLayout);
        activatePropertyContainerPanelLayout.setHorizontalGroup(
            activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activatePropertyMinClientsField)
                    .addComponent(activatePropertyMaxClientsField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activatePropertyMinClientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activatePropertyMaxClientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activatePropertyNRoomsField)
                    .addComponent(activatePropertyNBathroomsField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activatePropertyNRoomsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activatePropertyNBathroomsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(activatePropertyContainerPanelLayout.createSequentialGroup()
                        .addComponent(activatePropertyNBedsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(activatePropertyNBedsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(activatePropertyBedsTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(activatePropertyExtrasLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activatePropertyKitchenCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activatePropertyWashingMachineCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activatePropertyPoolCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        activatePropertyContainerPanelLayout.setVerticalGroup(
            activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activatePropertyMinClientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activatePropertyMinClientsLabel)
                    .addComponent(activatePropertyNRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activatePropertyNRoomsLabel)
                    .addComponent(activatePropertyNBedsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activatePropertyNBedsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activatePropertyContainerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(activatePropertyContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activatePropertyMaxClientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activatePropertyMaxClientsLabel)
                            .addComponent(activatePropertyNBathroomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activatePropertyNBathroomsLabel)))
                    .addComponent(activatePropertyBedsTypeBox))
                .addGap(51, 51, 51))
            .addGroup(activatePropertyContainerPanelLayout.createSequentialGroup()
                .addComponent(activatePropertyExtrasLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(activatePropertyContainerPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(activatePropertyKitchenCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activatePropertyWashingMachineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activatePropertyPoolCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout activatePropertyCharacteristicsPanelLayout = new javax.swing.GroupLayout(activatePropertyCharacteristicsPanel);
        activatePropertyCharacteristicsPanel.setLayout(activatePropertyCharacteristicsPanelLayout);
        activatePropertyCharacteristicsPanelLayout.setHorizontalGroup(
            activatePropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyCharacteristicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(activatePropertyContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        activatePropertyCharacteristicsPanelLayout.setVerticalGroup(
            activatePropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyCharacteristicsPanelLayout.createSequentialGroup()
                .addComponent(activatePropertyContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        activatePropertyActivateButton.setBackground(new java.awt.Color(255, 0, 51));
        activatePropertyActivateButton.setText("Ativar");

        activatePropertyCancelButton.setText("Cancelar");

        javax.swing.GroupLayout activatePropertyErrorPanelLayout = new javax.swing.GroupLayout(activatePropertyErrorPanel);
        activatePropertyErrorPanel.setLayout(activatePropertyErrorPanelLayout);
        activatePropertyErrorPanelLayout.setHorizontalGroup(
            activatePropertyErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1074, Short.MAX_VALUE)
        );
        activatePropertyErrorPanelLayout.setVerticalGroup(
            activatePropertyErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout activatePropertyInfoInfoPanelLayout = new javax.swing.GroupLayout(activatePropertyInfoInfoPanel);
        activatePropertyInfoInfoPanel.setLayout(activatePropertyInfoInfoPanelLayout);
        activatePropertyInfoInfoPanelLayout.setHorizontalGroup(
            activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                        .addComponent(activatePropertyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activatePropertyScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(activatePropertyPontuationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                        .addComponent(activatePropertyPhotoField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activatePropertyLocation)
                            .addComponent(activatePropertyDescription)
                            .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                                .addComponent(activatePropertyType, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(activatePropertyDivisions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(activatePropertyDiscountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activatePropertyDicountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activatePropertyPercentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(activatePropertyAvailableDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(activatePropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activatePropertyCoinType, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                        .addComponent(activatePropertyActivateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activatePropertyCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(activatePropertyErrorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(activatePropertyCharacteristicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        activatePropertyInfoInfoPanelLayout.setVerticalGroup(
            activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activatePropertyPhotoField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                        .addComponent(activatePropertyLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(activatePropertyDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(activatePropertyType)
                            .addComponent(activatePropertyDivisions)
                            .addComponent(activatePropertyPrice)
                            .addComponent(activatePropertyCoinType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(activatePropertyAvailableDatePicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(activatePropertyPercentageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(activatePropertyDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(activatePropertyDicountTextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                        .addComponent(activatePropertyPontuationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activatePropertyScore, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(activatePropertyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activatePropertyActivateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activatePropertyCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(activatePropertyErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(activatePropertyInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(activatePropertyInfoInfoPanelLayout.createSequentialGroup()
                    .addGap(205, 205, 205)
                    .addComponent(activatePropertyCharacteristicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout activatePropertyInfoPanelLayout = new javax.swing.GroupLayout(activatePropertyInfoPanel);
        activatePropertyInfoPanel.setLayout(activatePropertyInfoPanelLayout);
        activatePropertyInfoPanelLayout.setHorizontalGroup(
            activatePropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activatePropertyInfoInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        activatePropertyInfoPanelLayout.setVerticalGroup(
            activatePropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activatePropertyInfoInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout activatePropertyPanelLayout = new javax.swing.GroupLayout(activatePropertyPanel);
        activatePropertyPanel.setLayout(activatePropertyPanelLayout);
        activatePropertyPanelLayout.setHorizontalGroup(
            activatePropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activatePropertyTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(activatePropertyLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(activatePropertyInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        activatePropertyPanelLayout.setVerticalGroup(
            activatePropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activatePropertyPanelLayout.createSequentialGroup()
                .addComponent(activatePropertyTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(activatePropertyLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activatePropertyInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activatePropertyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activatePropertyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activatePropertyMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activatePropertyMessageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activatePropertyMessageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activatePropertyActivateButton;
    private org.jdesktop.swingx.JXDatePicker activatePropertyAvailableDatePicker;
    private javax.swing.JComboBox activatePropertyBedsTypeBox;
    private javax.swing.JCheckBox activatePropertyBreakfastCheckBox;
    private javax.swing.JButton activatePropertyCancelButton;
    private javax.swing.JPanel activatePropertyCharacteristicsPanel;
    private javax.swing.JLabel activatePropertyCoinType;
    private javax.swing.JPanel activatePropertyContainerPanel;
    private javax.swing.JTextField activatePropertyDescription;
    private javax.swing.JTextField activatePropertyDicountTextField;
    private javax.swing.JLabel activatePropertyDiscountLabel;
    private javax.swing.JComboBox<String> activatePropertyDivisions;
    private javax.swing.JPanel activatePropertyErrorPanel;
    private javax.swing.JPanel activatePropertyExtrasLeftPanel;
    private javax.swing.JPanel activatePropertyInfoInfoPanel;
    private javax.swing.JPanel activatePropertyInfoPanel;
    private javax.swing.JCheckBox activatePropertyKitchenCheckBox;
    private javax.swing.JComboBox<String> activatePropertyLanguageBox;
    private javax.swing.JTextField activatePropertyLocation;
    private javax.swing.JPanel activatePropertyLogoPanel;
    private javax.swing.JTextField activatePropertyMaxClientsField;
    private javax.swing.JLabel activatePropertyMaxClientsLabel;
    private javax.swing.JButton activatePropertyMessageButton;
    private javax.swing.JTextField activatePropertyMinClientsField;
    private javax.swing.JLabel activatePropertyMinClientsLabel;
    private javax.swing.JTextField activatePropertyNBathroomsField;
    private javax.swing.JLabel activatePropertyNBathroomsLabel;
    private javax.swing.JTextField activatePropertyNBedsField;
    private javax.swing.JLabel activatePropertyNBedsLabel;
    private javax.swing.JTextField activatePropertyNRoomsField;
    private javax.swing.JLabel activatePropertyNRoomsLabel;
    private javax.swing.JLabel activatePropertyNameLabel;
    private javax.swing.JPanel activatePropertyPanel;
    private javax.swing.JLabel activatePropertyPercentageLabel;
    private javax.swing.JCheckBox activatePropertyPetsCheckBox;
    private javax.swing.JTextField activatePropertyPhotoField;
    private javax.swing.JLabel activatePropertyPontuationLabel;
    private javax.swing.JCheckBox activatePropertyPoolCheckBox;
    private javax.swing.JTextField activatePropertyPrice;
    private javax.swing.JList<String> activatePropertyRating;
    private java.awt.Label activatePropertyScore;
    private javax.swing.JScrollPane activatePropertyScrollPane;
    private javax.swing.JPanel activatePropertyTopBarPanel;
    private javax.swing.JComboBox<String> activatePropertyType;
    private javax.swing.JCheckBox activatePropertyWashingMachineCheckBox;
    private javax.swing.JCheckBox activatePropertyWifiCheckBox;
    // End of variables declaration//GEN-END:variables
}
