/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import projectoalojamento.Repository;

/**
 *
 * @author Rafael
 */
public class JPAdminMenu extends javax.swing.JPanel {

    private Application frame;
    private Repository repo;
    
    /**
     * Creates new form JPAdminMenu
     */
    public JPAdminMenu(Application frame,Repository repo, Object language) {
        initComponents();
        this.frame = frame;
        this.repo = repo;
        this.adminMenuLanguageBox.setSelectedItem(language);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        adminMenuPanel = new javax.swing.JPanel();
        adminMenuTopBarPanel = new javax.swing.JPanel();
        adminMenuLanguageBox = new javax.swing.JComboBox<>();
        adminMenuUserLabel = new javax.swing.JLabel();
        adminMenuLogoPanel = new javax.swing.JPanel();
        adminMenuInfoPanel = new javax.swing.JPanel();
        addPropertySideBar = new javax.swing.JPanel();
        addPropertyDepartmentButton = new javax.swing.JButton();
        addPropertyReceivedMessagesButton = new javax.swing.JButton();
        addPropertyAddAdminsButton = new javax.swing.JButton();
        addPropertyOtherDefinitionsButton = new javax.swing.JButton();
        adminMenuList = new javax.swing.JTabbedPane();
        addPropertyClientsList = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addPropertyOwnersList = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        addPropertyPropertiesList = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        addPropertyBookingsList = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        adminMenuLanguageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT", "EN" }));

        adminMenuUserLabel.setText("jLabel1");

        javax.swing.GroupLayout adminMenuTopBarPanelLayout = new javax.swing.GroupLayout(adminMenuTopBarPanel);
        adminMenuTopBarPanel.setLayout(adminMenuTopBarPanelLayout);
        adminMenuTopBarPanelLayout.setHorizontalGroup(
            adminMenuTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminMenuLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminMenuUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminMenuTopBarPanelLayout.setVerticalGroup(
            adminMenuTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminMenuTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminMenuLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminMenuUserLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminMenuLogoPanelLayout = new javax.swing.GroupLayout(adminMenuLogoPanel);
        adminMenuLogoPanel.setLayout(adminMenuLogoPanelLayout);
        adminMenuLogoPanelLayout.setHorizontalGroup(
            adminMenuLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        adminMenuLogoPanelLayout.setVerticalGroup(
            adminMenuLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        addPropertyDepartmentButton.setText("jButton1");

        addPropertyReceivedMessagesButton.setText("jButton2");

        addPropertyAddAdminsButton.setText("jButton3");

        addPropertyOtherDefinitionsButton.setText("jButton4");

        javax.swing.GroupLayout addPropertySideBarLayout = new javax.swing.GroupLayout(addPropertySideBar);
        addPropertySideBar.setLayout(addPropertySideBarLayout);
        addPropertySideBarLayout.setHorizontalGroup(
            addPropertySideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPropertySideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPropertySideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPropertyDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPropertyReceivedMessagesButton)
                    .addComponent(addPropertyAddAdminsButton)
                    .addComponent(addPropertyOtherDefinitionsButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        addPropertySideBarLayout.setVerticalGroup(
            addPropertySideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPropertySideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPropertyDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPropertyReceivedMessagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPropertyAddAdminsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPropertyOtherDefinitionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        addPropertyClientsList.setViewportView(jList1);

        adminMenuList.addTab("Clientes", addPropertyClientsList);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 5", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        addPropertyOwnersList.setViewportView(jList2);

        adminMenuList.addTab("Donos", addPropertyOwnersList);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        addPropertyPropertiesList.setViewportView(jList3);

        adminMenuList.addTab("Alojamentos", addPropertyPropertiesList);

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        addPropertyBookingsList.setViewportView(jList4);

        adminMenuList.addTab("Reservas", addPropertyBookingsList);

        javax.swing.GroupLayout adminMenuInfoPanelLayout = new javax.swing.GroupLayout(adminMenuInfoPanel);
        adminMenuInfoPanel.setLayout(adminMenuInfoPanelLayout);
        adminMenuInfoPanelLayout.setHorizontalGroup(
            adminMenuInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminMenuInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminMenuList, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(addPropertySideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminMenuInfoPanelLayout.setVerticalGroup(
            adminMenuInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addPropertySideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminMenuInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminMenuList)
                .addContainerGap())
        );

        javax.swing.GroupLayout adminMenuPanelLayout = new javax.swing.GroupLayout(adminMenuPanel);
        adminMenuPanel.setLayout(adminMenuPanelLayout);
        adminMenuPanelLayout.setHorizontalGroup(
            adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminMenuTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminMenuLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminMenuInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminMenuPanelLayout.setVerticalGroup(
            adminMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMenuPanelLayout.createSequentialGroup()
                .addComponent(adminMenuTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminMenuLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminMenuInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPropertyAddAdminsButton;
    private javax.swing.JScrollPane addPropertyBookingsList;
    private javax.swing.JScrollPane addPropertyClientsList;
    private javax.swing.JButton addPropertyDepartmentButton;
    private javax.swing.JButton addPropertyOtherDefinitionsButton;
    private javax.swing.JScrollPane addPropertyOwnersList;
    private javax.swing.JScrollPane addPropertyPropertiesList;
    private javax.swing.JButton addPropertyReceivedMessagesButton;
    private javax.swing.JPanel addPropertySideBar;
    private javax.swing.JPanel adminMenuInfoPanel;
    private javax.swing.JComboBox<String> adminMenuLanguageBox;
    private javax.swing.JTabbedPane adminMenuList;
    private javax.swing.JPanel adminMenuLogoPanel;
    private javax.swing.JPanel adminMenuPanel;
    private javax.swing.JPanel adminMenuTopBarPanel;
    private javax.swing.JLabel adminMenuUserLabel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
