/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import javax.swing.JPanel;

/**
 *
 * @author Gustavo Vieira
 */
public class JPAfterLogin extends javax.swing.JPanel {

    private Application frame;
    //private JPLogin jpl;
    //private JPRegister jpr;
    private JPPropertySearch jpps;
    private JPProfile jpp;
    
    /**
     * Creates new form JPAfterLogin
     */
    public JPAfterLogin(Application frame, Object language) {
        initComponents();
        this.frame = frame;
        this.frame.setSize(1000, 253);
        
        /*if(panel instanceof JPLogin)
        {
            this.jpl = (JPLogin)panel;
        }
        else
        {
            this.jpr = (JPRegister)panel;
        }*/
        this.afterLoginLanguageBox.setSelectedItem(language);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afterLoginPanel = new javax.swing.JPanel();
        afterLoginTopBarPanel = new javax.swing.JPanel();
        afterLoginLanguageBox = new javax.swing.JComboBox();
        afterLoginNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        afterLoginLogoPanel = new javax.swing.JPanel();
        afterLoginInfoPanel = new javax.swing.JPanel();
        afterLoginErrorPanel = new javax.swing.JPanel();
        afterLoginErrorLabel = new javax.swing.JLabel();
        afterLoginLocationField = new javax.swing.JTextField();
        afterLoginStartingDatePicker = new org.jdesktop.swingx.JXDatePicker();
        afterLoginEndingDatePicker = new org.jdesktop.swingx.JXDatePicker();
        afterLoginPropertyTypeBox = new javax.swing.JComboBox();
        afterLoginSearchButton = new javax.swing.JButton();
        afterLoginNClientsSpinner = new javax.swing.JSpinner();
        afterLoginNClientsLabel = new javax.swing.JLabel();

        afterLoginLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));
        afterLoginLanguageBox.setToolTipText("");

        afterLoginNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        afterLoginNameLabel.setText("Gustavo Moreira Vieira");
        afterLoginNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afterLoginNameLabelMouseClicked(evt);
            }
        });

        jButton1.setText("Acho que tem de ser button e nao label");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afterLoginTopBarPanelLayout = new javax.swing.GroupLayout(afterLoginTopBarPanel);
        afterLoginTopBarPanel.setLayout(afterLoginTopBarPanelLayout);
        afterLoginTopBarPanelLayout.setHorizontalGroup(
            afterLoginTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        afterLoginTopBarPanelLayout.setVerticalGroup(
            afterLoginTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afterLoginLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afterLoginNameLabel)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout afterLoginLogoPanelLayout = new javax.swing.GroupLayout(afterLoginLogoPanel);
        afterLoginLogoPanel.setLayout(afterLoginLogoPanelLayout);
        afterLoginLogoPanelLayout.setHorizontalGroup(
            afterLoginLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        afterLoginLogoPanelLayout.setVerticalGroup(
            afterLoginLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        afterLoginErrorLabel.setForeground(new java.awt.Color(240, 240, 240));
        afterLoginErrorLabel.setText(" ");

        javax.swing.GroupLayout afterLoginErrorPanelLayout = new javax.swing.GroupLayout(afterLoginErrorPanel);
        afterLoginErrorPanel.setLayout(afterLoginErrorPanelLayout);
        afterLoginErrorPanelLayout.setHorizontalGroup(
            afterLoginErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginErrorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginErrorLabel)
                .addGap(480, 480, 480))
        );
        afterLoginErrorPanelLayout.setVerticalGroup(
            afterLoginErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginErrorPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(afterLoginErrorLabel)
                .addContainerGap())
        );

        afterLoginLocationField.setText(" Procurar por localidade");

        afterLoginPropertyTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quarto", "Apartamento" }));

        afterLoginSearchButton.setText("Pesquisar");
        afterLoginSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginSearchButtonActionPerformed(evt);
            }
        });

        afterLoginNClientsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afterLoginNClientsLabel.setText("Nº Viajantes");

        javax.swing.GroupLayout afterLoginInfoPanelLayout = new javax.swing.GroupLayout(afterLoginInfoPanel);
        afterLoginInfoPanel.setLayout(afterLoginInfoPanelLayout);
        afterLoginInfoPanelLayout.setHorizontalGroup(
            afterLoginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(afterLoginInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginStartingDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginEndingDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginNClientsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginNClientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginPropertyTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        afterLoginInfoPanelLayout.setVerticalGroup(
            afterLoginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginLocationField)
                    .addComponent(afterLoginStartingDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afterLoginEndingDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afterLoginPropertyTypeBox)
                    .addComponent(afterLoginSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(afterLoginNClientsSpinner)
                    .addComponent(afterLoginNClientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(afterLoginErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout afterLoginPanelLayout = new javax.swing.GroupLayout(afterLoginPanel);
        afterLoginPanel.setLayout(afterLoginPanelLayout);
        afterLoginPanelLayout.setHorizontalGroup(
            afterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        afterLoginPanelLayout.setVerticalGroup(
            afterLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginPanelLayout.createSequentialGroup()
                .addComponent(afterLoginTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void afterLoginSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginSearchButtonActionPerformed
        // TODO add your handling code here:
        this.jpps = new JPPropertySearch(this.frame, this.afterLoginLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpps);
    }//GEN-LAST:event_afterLoginSearchButtonActionPerformed

    private void afterLoginNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afterLoginNameLabelMouseClicked
        // TODO add your handling code here:
        this.jpp = new JPProfile(this.frame, this.afterLoginLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpp);
    }//GEN-LAST:event_afterLoginNameLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jpp = new JPProfile(this.frame, this.afterLoginLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpp);
    }//GEN-LAST:event_jButton1ActionPerformed

        //frame.changePanel(this.jpl);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker afterLoginEndingDatePicker;
    private javax.swing.JLabel afterLoginErrorLabel;
    private javax.swing.JPanel afterLoginErrorPanel;
    private javax.swing.JPanel afterLoginInfoPanel;
    private javax.swing.JComboBox afterLoginLanguageBox;
    private javax.swing.JTextField afterLoginLocationField;
    private javax.swing.JPanel afterLoginLogoPanel;
    private javax.swing.JLabel afterLoginNClientsLabel;
    private javax.swing.JSpinner afterLoginNClientsSpinner;
    private javax.swing.JLabel afterLoginNameLabel;
    private javax.swing.JPanel afterLoginPanel;
    private javax.swing.JComboBox afterLoginPropertyTypeBox;
    private javax.swing.JButton afterLoginSearchButton;
    private org.jdesktop.swingx.JXDatePicker afterLoginStartingDatePicker;
    private javax.swing.JPanel afterLoginTopBarPanel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
