/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import projectoalojamento.Repository;
import user.Owner;

/**
 *
 * @author Rafael
 */
public class JPAfterLoginOwner extends javax.swing.JPanel {

    private Application frame;
    private JPProfile jpprof;
    private JPConfirmBooking jpcb;
    private JPAddProperty jpap;
    private Repository repo;
    
    
    
    
    /**
     * Creates new form JPAfterLoginOwner
     */
   
    public JPAfterLoginOwner(Application frame,Repository repo, Object language) {
        initComponents();
        this.frame = frame;
        this.frame.setSize(1000, 253);
        
        /*if(panel instanceof JPLogin)
        {
            this.jpl = (JPLogin)panel;
        }
        else
        {
            this.jpr = (JPRegister)panel;
        }*/
        this.afterLoginOwnerLanguageBox.setSelectedItem(language);
        this.repo=repo;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afterLoginOwnerPanel = new javax.swing.JPanel();
        afterLoginOwnerTopBarPanel = new javax.swing.JPanel();
        afterLoginOwnerLanguageBox = new javax.swing.JComboBox<>();
        afterLoginOwnerNickLabel = new javax.swing.JLabel();
        afterLoginOwnerMessageButton = new javax.swing.JButton();
        afterLoginOwnerAddPropertyButton = new javax.swing.JButton();
        afterLoginOwnerTitlePanel = new javax.swing.JPanel();
        afterLoginOwnerInfoPanel = new javax.swing.JPanel();
        afterLoginOwnerErrorPanel = new javax.swing.JPanel();
        afterLoginOwnerInformationPanel = new javax.swing.JPanel();
        afterLoginOwnerPhotos = new javax.swing.JTextField();
        afterLoginOwnerDescriptionTextField = new javax.swing.JTextField();
        afterLoginOwnerLocationTextField = new javax.swing.JTextField();
        afterLoginOwnerTypeBox = new javax.swing.JComboBox<>();
        afterLoginOwnerDivisionsBox = new javax.swing.JComboBox<>();
        afterLoginOwnerDiscountLabel = new javax.swing.JLabel();
        afterLoginOwnerDiscountTextField = new javax.swing.JTextField();
        afterLoginOwnerPercentageLabel = new javax.swing.JLabel();
        afterLoginOwnerDatePicker = new org.jdesktop.swingx.JXDatePicker();
        afterLoginOwnerPriceTextField = new javax.swing.JTextField();
        afterLoginOwnerCoinTypeLabel = new javax.swing.JLabel();
        afterLoginOwnerScoreLabel = new java.awt.Label();
        afterLoginOwnerPontuationLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        afterLoginOwnerRating = new javax.swing.JList<>();
        afterLoginOwnerExtraSearchInfoPanel = new javax.swing.JPanel();
        afterLoginOwnerNClientsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNRoomsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNBathroomsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNBedsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNClientsLabel = new javax.swing.JLabel();
        afterLoginOwnerNRoomsLabel = new javax.swing.JLabel();
        afterLoginOwnerNBathroomssLabel = new javax.swing.JLabel();
        afterLoginOwnerNBedsLabel = new javax.swing.JLabel();
        afterLoginOwnerBedTypeBox = new javax.swing.JComboBox();
        afterLoginOwnerInfoExtraInfoPanel = new javax.swing.JPanel();
        afterLoginOwnerDiscountsCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerExtrasCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerRatingsCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerPetsCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerKitchenCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerWashingMachineCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerWifiCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerBreakfastCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerPoolCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerPreviousButton = new javax.swing.JButton();
        afterLoginOwnerNextButton = new javax.swing.JButton();
        afterLoginOwnerBookingButton = new javax.swing.JButton();
        afterLoginOwnerDeletePropertyButton = new javax.swing.JButton();
        afterLoginOwnerSaveChangesButton = new javax.swing.JButton();
        afterLoginOwnerCancelChangesButton = new javax.swing.JButton();

        afterLoginOwnerLanguageBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT", "EN" }));

        afterLoginOwnerNickLabel.setText("Rafael Morais");
        afterLoginOwnerNickLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afterLoginOwnerNickLabelMouseClicked(evt);
            }
        });
        afterLoginOwnerNickLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                afterLoginOwnerNickLabelPropertyChange(evt);
            }
        });

        afterLoginOwnerMessageButton.setText("jButton7");
        afterLoginOwnerMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerMessageButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerAddPropertyButton.setText("+");
        afterLoginOwnerAddPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerAddPropertyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afterLoginOwnerTopBarPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerTopBarPanel);
        afterLoginOwnerTopBarPanel.setLayout(afterLoginOwnerTopBarPanelLayout);
        afterLoginOwnerTopBarPanelLayout.setHorizontalGroup(
            afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginOwnerLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginOwnerAddPropertyButton)
                .addGap(18, 18, 18)
                .addComponent(afterLoginOwnerMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(afterLoginOwnerNickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        afterLoginOwnerTopBarPanelLayout.setVerticalGroup(
            afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerLanguageBox)
                    .addGroup(afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(afterLoginOwnerNickLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(afterLoginOwnerMessageButton)
                        .addComponent(afterLoginOwnerAddPropertyButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout afterLoginOwnerTitlePanelLayout = new javax.swing.GroupLayout(afterLoginOwnerTitlePanel);
        afterLoginOwnerTitlePanel.setLayout(afterLoginOwnerTitlePanelLayout);
        afterLoginOwnerTitlePanelLayout.setHorizontalGroup(
            afterLoginOwnerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        afterLoginOwnerTitlePanelLayout.setVerticalGroup(
            afterLoginOwnerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout afterLoginOwnerErrorPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerErrorPanel);
        afterLoginOwnerErrorPanel.setLayout(afterLoginOwnerErrorPanelLayout);
        afterLoginOwnerErrorPanelLayout.setHorizontalGroup(
            afterLoginOwnerErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        afterLoginOwnerErrorPanelLayout.setVerticalGroup(
            afterLoginOwnerErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        afterLoginOwnerPhotos.setText("jTextField1");

        afterLoginOwnerDescriptionTextField.setText("jTextField2");

        afterLoginOwnerLocationTextField.setText("ola");

        afterLoginOwnerTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa" }));

        afterLoginOwnerDivisionsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1", "T2", "T3", "T4", "T5" }));

        afterLoginOwnerDiscountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afterLoginOwnerDiscountLabel.setText("Desconto:");

        afterLoginOwnerDiscountTextField.setText("jTextField4");

        afterLoginOwnerPercentageLabel.setText("%");

        afterLoginOwnerPriceTextField.setText("jTextField5");

        afterLoginOwnerCoinTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afterLoginOwnerCoinTypeLabel.setText("€");

        afterLoginOwnerScoreLabel.setAlignment(java.awt.Label.CENTER);
        afterLoginOwnerScoreLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        afterLoginOwnerScoreLabel.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        afterLoginOwnerScoreLabel.setText("8.7");

        afterLoginOwnerPontuationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afterLoginOwnerPontuationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afterLoginOwnerPontuationLabel.setText("PONTUAÇÃO");

        afterLoginOwnerRating.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(afterLoginOwnerRating);

        afterLoginOwnerExtraSearchInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação Extra"));

        afterLoginOwnerNRoomsSpinner.setToolTipText("Número mínimo de quartos do alojamento");

        afterLoginOwnerNBathroomsSpinner.setToolTipText("Número mínimo de quartos de banho do alojamento");

        afterLoginOwnerNBedsSpinner.setToolTipText("Número mínimo de camas do alojamento");

        afterLoginOwnerNClientsLabel.setText("Nº Pessoas");

        afterLoginOwnerNRoomsLabel.setText("Nº Quartos");

        afterLoginOwnerNBathroomssLabel.setText("Nº Quartos de Banho");

        afterLoginOwnerNBedsLabel.setText("Nº Camas");

        afterLoginOwnerBedTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de Cama" }));

        afterLoginOwnerInfoExtraInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));

        afterLoginOwnerDiscountsCheckBox.setText("Contém descontos");

        afterLoginOwnerExtrasCheckBox.setText("Contém extras");

        afterLoginOwnerRatingsCheckBox.setText("Contém avaliações");

        afterLoginOwnerPetsCheckBox.setText("Animais de Estimação");

        afterLoginOwnerKitchenCheckBox.setText("Cozinha");

        afterLoginOwnerWashingMachineCheckBox.setText("Máquina de Lavar");

        afterLoginOwnerWifiCheckBox.setText("Wi-fi");

        afterLoginOwnerBreakfastCheckBox.setText("Pequeno Almoço");

        afterLoginOwnerPoolCheckBox.setText("Piscina");

        javax.swing.GroupLayout afterLoginOwnerInfoExtraInfoPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerInfoExtraInfoPanel);
        afterLoginOwnerInfoExtraInfoPanel.setLayout(afterLoginOwnerInfoExtraInfoPanelLayout);
        afterLoginOwnerInfoExtraInfoPanelLayout.setHorizontalGroup(
            afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afterLoginOwnerPetsCheckBox)
                    .addComponent(afterLoginOwnerWashingMachineCheckBox)
                    .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerDiscountsCheckBox)
                            .addComponent(afterLoginOwnerKitchenCheckBox)
                            .addComponent(afterLoginOwnerWifiCheckBox))
                        .addGap(16, 16, 16)
                        .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerPoolCheckBox)
                            .addComponent(afterLoginOwnerBreakfastCheckBox)
                            .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                                .addComponent(afterLoginOwnerExtrasCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(afterLoginOwnerRatingsCheckBox)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        afterLoginOwnerInfoExtraInfoPanelLayout.setVerticalGroup(
            afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afterLoginOwnerDiscountsCheckBox)
                    .addComponent(afterLoginOwnerExtrasCheckBox)
                    .addComponent(afterLoginOwnerRatingsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerPetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afterLoginOwnerKitchenCheckBox)
                    .addComponent(afterLoginOwnerBreakfastCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerWashingMachineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afterLoginOwnerWifiCheckBox)
                    .addComponent(afterLoginOwnerPoolCheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout afterLoginOwnerExtraSearchInfoPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerExtraSearchInfoPanel);
        afterLoginOwnerExtraSearchInfoPanel.setLayout(afterLoginOwnerExtraSearchInfoPanelLayout);
        afterLoginOwnerExtraSearchInfoPanelLayout.setHorizontalGroup(
            afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerNClientsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(afterLoginOwnerNRoomsSpinner)
                    .addComponent(afterLoginOwnerNBathroomsSpinner)
                    .addComponent(afterLoginOwnerNBedsSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerNBathroomssLabel)
                            .addComponent(afterLoginOwnerNRoomsLabel))
                        .addGap(262, 262, 262))
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                                .addComponent(afterLoginOwnerNClientsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(afterLoginOwnerBedTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(afterLoginOwnerNBedsLabel))
                        .addGap(18, 18, 18)))
                .addComponent(afterLoginOwnerInfoExtraInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        afterLoginOwnerExtraSearchInfoPanelLayout.setVerticalGroup(
            afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(afterLoginOwnerInfoExtraInfoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afterLoginOwnerNClientsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterLoginOwnerNClientsLabel)
                            .addComponent(afterLoginOwnerBedTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afterLoginOwnerNRoomsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterLoginOwnerNRoomsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afterLoginOwnerNBathroomsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterLoginOwnerNBathroomssLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afterLoginOwnerNBedsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterLoginOwnerNBedsLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout afterLoginOwnerInformationPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerInformationPanel);
        afterLoginOwnerInformationPanel.setLayout(afterLoginOwnerInformationPanelLayout);
        afterLoginOwnerInformationPanelLayout.setHorizontalGroup(
            afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerScoreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerPontuationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerLocationTextField)
                            .addComponent(afterLoginOwnerDescriptionTextField)
                            .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                                .addComponent(afterLoginOwnerTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(afterLoginOwnerDivisionsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(afterLoginOwnerDiscountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerDiscountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerPercentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(afterLoginOwnerDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(afterLoginOwnerPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerCoinTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(afterLoginOwnerExtraSearchInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        afterLoginOwnerInformationPanelLayout.setVerticalGroup(
            afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(afterLoginOwnerDescriptionTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(afterLoginOwnerTypeBox)
                            .addComponent(afterLoginOwnerDivisionsBox)
                            .addComponent(afterLoginOwnerPriceTextField)
                            .addComponent(afterLoginOwnerCoinTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerDatePicker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerPercentageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerDiscountTextField))))
                .addGap(18, 18, 18)
                .addComponent(afterLoginOwnerExtraSearchInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerPontuationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(afterLoginOwnerScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        afterLoginOwnerPreviousButton.setText("ANTERIOR");
        afterLoginOwnerPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerPreviousButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerNextButton.setText("SEGUINTE");

        afterLoginOwnerBookingButton.setText("RESERVAS");
        afterLoginOwnerBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerBookingButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerDeletePropertyButton.setText("ELIMINAR ALOJAMENTO");

        afterLoginOwnerSaveChangesButton.setText("GUARDAR ALTERAÇÕES");
        afterLoginOwnerSaveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerSaveChangesButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerCancelChangesButton.setText("CANCELAR ALTERAÇÕES");

        javax.swing.GroupLayout afterLoginOwnerInfoPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerInfoPanel);
        afterLoginOwnerInfoPanel.setLayout(afterLoginOwnerInfoPanelLayout);
        afterLoginOwnerInfoPanelLayout.setHorizontalGroup(
            afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginOwnerInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginOwnerPreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(afterLoginOwnerDeletePropertyButton))
                    .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerSaveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(afterLoginOwnerCancelChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginOwnerNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        afterLoginOwnerInfoPanelLayout.setVerticalGroup(
            afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                .addComponent(afterLoginOwnerInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afterLoginOwnerNextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(afterLoginOwnerCancelChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerSaveChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afterLoginOwnerDeletePropertyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterLoginOwnerBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(afterLoginOwnerPreviousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(afterLoginOwnerErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout afterLoginOwnerPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerPanel);
        afterLoginOwnerPanel.setLayout(afterLoginOwnerPanelLayout);
        afterLoginOwnerPanelLayout.setHorizontalGroup(
            afterLoginOwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginOwnerTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginOwnerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        afterLoginOwnerPanelLayout.setVerticalGroup(
            afterLoginOwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerPanelLayout.createSequentialGroup()
                .addComponent(afterLoginOwnerTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void afterLoginOwnerPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerPreviousButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afterLoginOwnerPreviousButtonActionPerformed

    private void afterLoginOwnerSaveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerSaveChangesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afterLoginOwnerSaveChangesButtonActionPerformed

    private void afterLoginOwnerAddPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerAddPropertyButtonActionPerformed
        // TODO add your handling code here:
         this.jpap = new JPAddProperty(this.frame, this.repo, this.afterLoginOwnerLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpap);
    }//GEN-LAST:event_afterLoginOwnerAddPropertyButtonActionPerformed

    private void afterLoginOwnerMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerMessageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afterLoginOwnerMessageButtonActionPerformed

    private void afterLoginOwnerNickLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afterLoginOwnerNickLabelMouseClicked
        // TODO add your handling code here:
        this.jpprof = new JPProfile(this.frame, this.repo,this.afterLoginOwnerLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpprof);
    }//GEN-LAST:event_afterLoginOwnerNickLabelMouseClicked

    private void afterLoginOwnerBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerBookingButtonActionPerformed
        // TODO add your handling code here:
        this.jpcb = new JPConfirmBooking(this.frame, this.repo,this.afterLoginOwnerLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpcb);
    }//GEN-LAST:event_afterLoginOwnerBookingButtonActionPerformed

    private void afterLoginOwnerNickLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_afterLoginOwnerNickLabelPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_afterLoginOwnerNickLabelPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afterLoginOwnerAddPropertyButton;
    private javax.swing.JComboBox afterLoginOwnerBedTypeBox;
    private javax.swing.JButton afterLoginOwnerBookingButton;
    private javax.swing.JCheckBox afterLoginOwnerBreakfastCheckBox;
    private javax.swing.JButton afterLoginOwnerCancelChangesButton;
    private javax.swing.JLabel afterLoginOwnerCoinTypeLabel;
    private org.jdesktop.swingx.JXDatePicker afterLoginOwnerDatePicker;
    private javax.swing.JButton afterLoginOwnerDeletePropertyButton;
    private javax.swing.JTextField afterLoginOwnerDescriptionTextField;
    private javax.swing.JLabel afterLoginOwnerDiscountLabel;
    private javax.swing.JTextField afterLoginOwnerDiscountTextField;
    private javax.swing.JCheckBox afterLoginOwnerDiscountsCheckBox;
    private javax.swing.JComboBox<String> afterLoginOwnerDivisionsBox;
    private javax.swing.JPanel afterLoginOwnerErrorPanel;
    private javax.swing.JPanel afterLoginOwnerExtraSearchInfoPanel;
    private javax.swing.JCheckBox afterLoginOwnerExtrasCheckBox;
    private javax.swing.JPanel afterLoginOwnerInfoExtraInfoPanel;
    private javax.swing.JPanel afterLoginOwnerInfoPanel;
    private javax.swing.JPanel afterLoginOwnerInformationPanel;
    private javax.swing.JCheckBox afterLoginOwnerKitchenCheckBox;
    private javax.swing.JComboBox<String> afterLoginOwnerLanguageBox;
    private javax.swing.JTextField afterLoginOwnerLocationTextField;
    private javax.swing.JButton afterLoginOwnerMessageButton;
    private javax.swing.JSpinner afterLoginOwnerNBathroomsSpinner;
    private javax.swing.JLabel afterLoginOwnerNBathroomssLabel;
    private javax.swing.JLabel afterLoginOwnerNBedsLabel;
    private javax.swing.JSpinner afterLoginOwnerNBedsSpinner;
    private javax.swing.JLabel afterLoginOwnerNClientsLabel;
    private javax.swing.JSpinner afterLoginOwnerNClientsSpinner;
    private javax.swing.JLabel afterLoginOwnerNRoomsLabel;
    private javax.swing.JSpinner afterLoginOwnerNRoomsSpinner;
    private javax.swing.JButton afterLoginOwnerNextButton;
    private javax.swing.JLabel afterLoginOwnerNickLabel;
    private javax.swing.JPanel afterLoginOwnerPanel;
    private javax.swing.JLabel afterLoginOwnerPercentageLabel;
    private javax.swing.JCheckBox afterLoginOwnerPetsCheckBox;
    private javax.swing.JTextField afterLoginOwnerPhotos;
    private javax.swing.JLabel afterLoginOwnerPontuationLabel;
    private javax.swing.JCheckBox afterLoginOwnerPoolCheckBox;
    private javax.swing.JButton afterLoginOwnerPreviousButton;
    private javax.swing.JTextField afterLoginOwnerPriceTextField;
    private javax.swing.JList<String> afterLoginOwnerRating;
    private javax.swing.JCheckBox afterLoginOwnerRatingsCheckBox;
    private javax.swing.JButton afterLoginOwnerSaveChangesButton;
    private java.awt.Label afterLoginOwnerScoreLabel;
    private javax.swing.JPanel afterLoginOwnerTitlePanel;
    private javax.swing.JPanel afterLoginOwnerTopBarPanel;
    private javax.swing.JComboBox<String> afterLoginOwnerTypeBox;
    private javax.swing.JCheckBox afterLoginOwnerWashingMachineCheckBox;
    private javax.swing.JCheckBox afterLoginOwnerWifiCheckBox;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
