/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import projectoalojamento.Repository;
import property.Discount;
import property.Property;
import property.PropertyCharacteristics;
import property.PropertyType;
import property.Room;
import property.location.County;
import user.Owner;
import user.User;


/**
 *
 * @author Rafael
 */
public class JPAfterLoginOwner extends javax.swing.JPanel {

    private Application frame;
    private JPProfile jpprof;
    private JPConfirmBooking jpcb;
    private JPAddProperty jpap;
    private Owner owner;
    private int position = 0;
    private int count;
    private Map<Property, County> map ;
    private Property p;
    
    /**
     * Creates new form JPAfterLoginOwner
     */
   
    public JPAfterLoginOwner(Application frame, Owner owner, Object language) {
        initComponents();
        this.frame = frame;
        this.frame.setSize(1000, 782);
        this.owner = owner;
        this.afterLoginOwnerNickLabel.setText(this.owner.getName());
        count = Repository.getRepo().nPropertiesByOwner(this.owner);
        map = Repository.getRepo().getPropertyByOwner(this.owner);
        /*if(panel instanceof JPLogin)
        {
            this.jpl = (JPLogin)panel;
        }
        else
        {
            this.jpr = (JPRegister)panel;
        }*/
        this.afterLoginOwnerLanguageBox.setSelectedItem(language);
        if(count!= 0){
            this.p = Repository.getRepo().currentProperty(this.map,this.position);
            writeData(this.p);
           
        }
   
        if(position == 0)
        {
            this.afterLoginOwnerPreviousButton.setEnabled(false);
        }
        
        if(count <= 1)
        {
            this.afterLoginOwnerNextButton.setEnabled(false);
        }
   
    }
    
    
    
    public void writeData(Property p){
        afterLoginOwnerDescriptionTextArea.setText(p.getDescription());
        afterLoginOwnerTypeBox.setSelectedItem(p.getPropertyType());
        afterLoginOwnerDiscountTextField.setText(String.valueOf(p.getDiscount().getPercentage()));
        afterLoginOwnerLocationBox.setSelectedItem(map.get(p));
        afterLoginOwnerPriceTextField.setText(String.valueOf(p.getPricePerNight()));
        afterLoginOwnerNMinClientsSpinner.setValue(p.getCharacteristics().getMinClients());
        afterLoginOwnerNMaxClientsSpinner.setValue(p.getCharacteristics().getMaxClients());
        afterLoginOwnerNRoomsSpinner.setValue(p.getCharacteristics().getRoomsQuantity());
        afterLoginOwnerNBathroomsSpinner.setValue(p.getCharacteristics().getBathroomQuantity());
        afterLoginOwnerNBedsSpinner.setValue(Repository.getRepo().nBeds(p));
        afterLoginOwnerPetsCheckBox.setSelected(p.getCharacteristics().isPets());
        afterLoginOwnerPoolCheckBox.setSelected(p.getCharacteristics().isPool());
        afterLoginOwnerKitchenCheckBox.setSelected(p.getCharacteristics().isKitchen());
        afterLoginOwnerWashingMachineCheckBox.setSelected(p.getCharacteristics().isWashingMachine());
        afterLoginOwnerWifiCheckBox.setSelected(p.getCharacteristics().isWifi());
        afterLoginOwnerBreakfastCheckBox.setSelected(p.getCharacteristics().isBreakfast());
        this.afterLoginOwnerLocationBox.setModel(new DefaultComboBoxModel(Repository.getRepo().getCounties().toArray()));
        this.afterLoginOwnerLocationBox.setSelectedItem(this.map.get(this.p));
        this.afterLoginOwnerTypeBox.setModel(new DefaultComboBoxModel(Repository.getRepo().getPropertiesTypes().toArray()));
        this.afterLoginOwnerTypeBox.setSelectedItem(this.p.getPropertyType());
        this.afterLoginOwnerNameField.setText(this.p.getName());
        this.afterLoginOwnerScoreLabel.setText(String.valueOf(this.p.getPropertyRatingMedianPoints()));
    }
              
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afterLoginOwnerPanel = new javax.swing.JPanel();
        afterLoginOwnerTopBarPanel = new javax.swing.JPanel();
        afterLoginOwnerLanguageBox = new javax.swing.JComboBox<String>();
        afterLoginOwnerNickLabel = new javax.swing.JLabel();
        afterLoginOwnerMessageButton = new javax.swing.JButton();
        afterLoginOwnerAddPropertyButton = new javax.swing.JButton();
        afterLoginOwnerTitlePanel = new javax.swing.JPanel();
        afterLoginOwnerInfoPanel = new javax.swing.JPanel();
        afterLoginOwnerInformationPanel = new javax.swing.JPanel();
        afterLoginOwnerPhotos = new javax.swing.JTextField();
        afterLoginOwnerTypeBox = new javax.swing.JComboBox<String>();
        afterLoginOwnerDiscountLabel = new javax.swing.JLabel();
        afterLoginOwnerDiscountTextField = new javax.swing.JTextField();
        afterLoginOwnerPercentageLabel = new javax.swing.JLabel();
        afterLoginOwnerPriceTextField = new javax.swing.JTextField();
        afterLoginOwnerCoinTypeLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        afterLoginOwnerRating = new javax.swing.JList<String>();
        afterLoginOwnerExtraSearchInfoPanel = new javax.swing.JPanel();
        afterLoginOwnerNMinClientsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNRoomsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNBathroomsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNBedsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNMinClientsLabel = new javax.swing.JLabel();
        afterLoginOwnerNRoomsLabel = new javax.swing.JLabel();
        afterLoginOwnerNBathroomssLabel = new javax.swing.JLabel();
        afterLoginOwnerNBedsLabel = new javax.swing.JLabel();
        afterLoginOwnerInfoExtraInfoPanel = new javax.swing.JPanel();
        afterLoginOwnerExtrasCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerPetsCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerKitchenCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerWashingMachineCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerWifiCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerBreakfastCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerPoolCheckBox = new javax.swing.JCheckBox();
        afterLoginOwnerNMaxClientsSpinner = new javax.swing.JSpinner();
        afterLoginOwnerNMaxClientsLabel = new javax.swing.JLabel();
        afterLoginOwnerPontuationLabel = new javax.swing.JLabel();
        afterLoginOwnerScoreLabel = new java.awt.Label();
        afterLoginOwnerLocationBox = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        afterLoginOwnerDescriptionTextArea = new javax.swing.JTextArea();
        afterLoginOwnerNameField = new javax.swing.JTextField();
        afterLoginOwnerPreviousButton = new javax.swing.JButton();
        afterLoginOwnerNextButton = new javax.swing.JButton();
        afterLoginOwnerBookingButton = new javax.swing.JButton();
        afterLoginOwnerDeletePropertyButton = new javax.swing.JButton();
        afterLoginOwnerSaveChangesButton = new javax.swing.JButton();
        afterLoginOwnerCancelChangesButton = new javax.swing.JButton();
        afterLoginOwnerErrorPanel = new javax.swing.JPanel();
        afterLoginOwnerErrorLabel = new javax.swing.JLabel();

        afterLoginOwnerLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));

        afterLoginOwnerNickLabel.setText("Rafael Morais");
        afterLoginOwnerNickLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afterLoginOwnerNickLabelMouseClicked(evt);
            }
        });
        afterLoginOwnerNickLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                afterLoginOwnerNickLabelPropertyChange(evt);
            }
        });

        afterLoginOwnerMessageButton.setText("jButton7");
        afterLoginOwnerMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerMessageButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerAddPropertyButton.setText("+");
        afterLoginOwnerAddPropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerAddPropertyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afterLoginOwnerTopBarPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerTopBarPanel);
        afterLoginOwnerTopBarPanel.setLayout(afterLoginOwnerTopBarPanelLayout);
        afterLoginOwnerTopBarPanelLayout.setHorizontalGroup(
            afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginOwnerLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginOwnerAddPropertyButton)
                .addGap(18, 18, 18)
                .addComponent(afterLoginOwnerMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(afterLoginOwnerNickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        afterLoginOwnerTopBarPanelLayout.setVerticalGroup(
            afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerLanguageBox)
                    .addGroup(afterLoginOwnerTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(afterLoginOwnerNickLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(afterLoginOwnerMessageButton)
                        .addComponent(afterLoginOwnerAddPropertyButton)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout afterLoginOwnerTitlePanelLayout = new javax.swing.GroupLayout(afterLoginOwnerTitlePanel);
        afterLoginOwnerTitlePanel.setLayout(afterLoginOwnerTitlePanelLayout);
        afterLoginOwnerTitlePanelLayout.setHorizontalGroup(
            afterLoginOwnerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        afterLoginOwnerTitlePanelLayout.setVerticalGroup(
            afterLoginOwnerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        afterLoginOwnerPhotos.setText("jTextField1");

        afterLoginOwnerTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apartamento", "Casa" }));

        afterLoginOwnerDiscountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afterLoginOwnerDiscountLabel.setText("Desconto:");

        afterLoginOwnerDiscountTextField.setText("jTextField4");
        afterLoginOwnerDiscountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                afterLoginOwnerDiscountTextFieldFocusLost(evt);
            }
        });

        afterLoginOwnerPercentageLabel.setText("%");

        afterLoginOwnerPriceTextField.setText("jTextField5");
        afterLoginOwnerPriceTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                afterLoginOwnerPriceTextFieldFocusLost(evt);
            }
        });

        afterLoginOwnerCoinTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afterLoginOwnerCoinTypeLabel.setText("€");

        afterLoginOwnerRating.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(afterLoginOwnerRating);

        afterLoginOwnerExtraSearchInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação Extra"));

        afterLoginOwnerNRoomsSpinner.setToolTipText("Número mínimo de quartos do alojamento");

        afterLoginOwnerNBathroomsSpinner.setToolTipText("Número mínimo de quartos de banho do alojamento");

        afterLoginOwnerNBedsSpinner.setToolTipText("Número mínimo de camas do alojamento");

        afterLoginOwnerNMinClientsLabel.setText("Nº Min Pessoas");

        afterLoginOwnerNRoomsLabel.setText("Nº Quartos");

        afterLoginOwnerNBathroomssLabel.setText("Nº Quartos de Banho");

        afterLoginOwnerNBedsLabel.setText("Nº Camas");

        afterLoginOwnerInfoExtraInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));

        afterLoginOwnerExtrasCheckBox.setText("Contém extras");

        afterLoginOwnerPetsCheckBox.setText("Animais de Estimação");

        afterLoginOwnerKitchenCheckBox.setText("Cozinha");

        afterLoginOwnerWashingMachineCheckBox.setText("Máquina de Lavar");

        afterLoginOwnerWifiCheckBox.setText("Wi-fi");

        afterLoginOwnerBreakfastCheckBox.setText("Pequeno Almoço");

        afterLoginOwnerPoolCheckBox.setText("Piscina");

        javax.swing.GroupLayout afterLoginOwnerInfoExtraInfoPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerInfoExtraInfoPanel);
        afterLoginOwnerInfoExtraInfoPanel.setLayout(afterLoginOwnerInfoExtraInfoPanelLayout);
        afterLoginOwnerInfoExtraInfoPanelLayout.setHorizontalGroup(
            afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afterLoginOwnerPetsCheckBox)
                    .addComponent(afterLoginOwnerWashingMachineCheckBox)
                    .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerKitchenCheckBox)
                            .addComponent(afterLoginOwnerWifiCheckBox)
                            .addComponent(afterLoginOwnerPoolCheckBox))
                        .addGap(68, 68, 68)
                        .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerBreakfastCheckBox)
                            .addComponent(afterLoginOwnerExtrasCheckBox))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        afterLoginOwnerInfoExtraInfoPanelLayout.setVerticalGroup(
            afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createSequentialGroup()
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afterLoginOwnerExtrasCheckBox)
                    .addComponent(afterLoginOwnerPoolCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerPetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(afterLoginOwnerInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afterLoginOwnerKitchenCheckBox)
                    .addComponent(afterLoginOwnerBreakfastCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerWashingMachineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerWifiCheckBox)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        afterLoginOwnerNMaxClientsLabel.setText("Nº Max Pessoas");

        afterLoginOwnerPontuationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afterLoginOwnerPontuationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        afterLoginOwnerPontuationLabel.setText("PONTUAÇÃO");

        afterLoginOwnerScoreLabel.setAlignment(java.awt.Label.CENTER);
        afterLoginOwnerScoreLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        afterLoginOwnerScoreLabel.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        afterLoginOwnerScoreLabel.setText("8.7");

        javax.swing.GroupLayout afterLoginOwnerExtraSearchInfoPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerExtraSearchInfoPanel);
        afterLoginOwnerExtraSearchInfoPanel.setLayout(afterLoginOwnerExtraSearchInfoPanelLayout);
        afterLoginOwnerExtraSearchInfoPanelLayout.setHorizontalGroup(
            afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerNMinClientsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(afterLoginOwnerNRoomsSpinner)
                    .addComponent(afterLoginOwnerNBathroomsSpinner)
                    .addComponent(afterLoginOwnerNBedsSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerNBathroomssLabel)
                            .addComponent(afterLoginOwnerNRoomsLabel))
                        .addGap(262, 262, 262))
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(afterLoginOwnerNBedsLabel)
                            .addComponent(afterLoginOwnerNMinClientsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(afterLoginOwnerNMaxClientsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(afterLoginOwnerNMaxClientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginOwnerInfoExtraInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerPontuationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(afterLoginOwnerScoreLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        afterLoginOwnerExtraSearchInfoPanelLayout.setVerticalGroup(
            afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(afterLoginOwnerInfoExtraInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(afterLoginOwnerNMaxClientsSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(afterLoginOwnerNMinClientsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(afterLoginOwnerNMinClientsLabel)
                                        .addComponent(afterLoginOwnerNMaxClientsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(afterLoginOwnerNRoomsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(afterLoginOwnerNRoomsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(afterLoginOwnerNBathroomsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(afterLoginOwnerNBathroomssLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(afterLoginOwnerNBedsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(afterLoginOwnerNBedsLabel)))))
                    .addGroup(afterLoginOwnerExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerPontuationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(afterLoginOwnerScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        afterLoginOwnerLocationBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        afterLoginOwnerDescriptionTextArea.setColumns(20);
        afterLoginOwnerDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(afterLoginOwnerDescriptionTextArea);

        javax.swing.GroupLayout afterLoginOwnerInformationPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerInformationPanel);
        afterLoginOwnerInformationPanel.setLayout(afterLoginOwnerInformationPanelLayout);
        afterLoginOwnerInformationPanelLayout.setHorizontalGroup(
            afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                                .addComponent(afterLoginOwnerTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(afterLoginOwnerDiscountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerDiscountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerPercentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerLocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(afterLoginOwnerPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afterLoginOwnerCoinTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(afterLoginOwnerNameField)))
                    .addComponent(afterLoginOwnerExtraSearchInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        afterLoginOwnerInformationPanelLayout.setVerticalGroup(
            afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerPhotos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(afterLoginOwnerInformationPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(afterLoginOwnerInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(afterLoginOwnerTypeBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerPriceTextField)
                            .addComponent(afterLoginOwnerCoinTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerPercentageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerDiscountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerDiscountTextField)
                            .addComponent(afterLoginOwnerLocationBox))))
                .addGap(18, 18, 18)
                .addComponent(afterLoginOwnerExtraSearchInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        afterLoginOwnerPreviousButton.setText("ANTERIOR");
        afterLoginOwnerPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerPreviousButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerNextButton.setText("SEGUINTE");
        afterLoginOwnerNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerNextButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerBookingButton.setText("RESERVAS");
        afterLoginOwnerBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerBookingButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerDeletePropertyButton.setText("ELIMINAR ALOJAMENTO");
        afterLoginOwnerDeletePropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerDeletePropertyButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerSaveChangesButton.setText("GUARDAR ALTERAÇÕES");
        afterLoginOwnerSaveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerSaveChangesButtonActionPerformed(evt);
            }
        });

        afterLoginOwnerCancelChangesButton.setText("CANCELAR ALTERAÇÕES");
        afterLoginOwnerCancelChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterLoginOwnerCancelChangesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout afterLoginOwnerInfoPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerInfoPanel);
        afterLoginOwnerInfoPanel.setLayout(afterLoginOwnerInfoPanelLayout);
        afterLoginOwnerInfoPanelLayout.setHorizontalGroup(
            afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginOwnerPreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(afterLoginOwnerDeletePropertyButton))
                    .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                        .addComponent(afterLoginOwnerSaveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(afterLoginOwnerCancelChangesButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(afterLoginOwnerNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        afterLoginOwnerInfoPanelLayout.setVerticalGroup(
            afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                .addComponent(afterLoginOwnerInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(afterLoginOwnerPreviousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(afterLoginOwnerInfoPanelLayout.createSequentialGroup()
                        .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(afterLoginOwnerSaveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afterLoginOwnerCancelChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(afterLoginOwnerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(afterLoginOwnerBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(afterLoginOwnerDeletePropertyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(afterLoginOwnerNextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        afterLoginOwnerErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout afterLoginOwnerErrorPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerErrorPanel);
        afterLoginOwnerErrorPanel.setLayout(afterLoginOwnerErrorPanelLayout);
        afterLoginOwnerErrorPanelLayout.setHorizontalGroup(
            afterLoginOwnerErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        afterLoginOwnerErrorPanelLayout.setVerticalGroup(
            afterLoginOwnerErrorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, afterLoginOwnerErrorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginOwnerErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout afterLoginOwnerPanelLayout = new javax.swing.GroupLayout(afterLoginOwnerPanel);
        afterLoginOwnerPanel.setLayout(afterLoginOwnerPanelLayout);
        afterLoginOwnerPanelLayout.setHorizontalGroup(
            afterLoginOwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginOwnerTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(afterLoginOwnerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(afterLoginOwnerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afterLoginOwnerErrorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        afterLoginOwnerPanelLayout.setVerticalGroup(
            afterLoginOwnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(afterLoginOwnerPanelLayout.createSequentialGroup()
                .addComponent(afterLoginOwnerTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterLoginOwnerErrorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(afterLoginOwnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void afterLoginOwnerPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerPreviousButtonActionPerformed
        // TODO add your handling code here:
        if(this.position>0){
            position--;
           this.p = Repository.getRepo().currentProperty(this.map,this.position);   
           this.writeData(p);
           
           if(this.position == 0)
           {
               this.afterLoginOwnerPreviousButton.setEnabled(false);
           }
           
           if(this.position >= 0 && this.position <= this.count - 1)
           {
               this.afterLoginOwnerNextButton.setEnabled(true);
           }
        }
    }//GEN-LAST:event_afterLoginOwnerPreviousButtonActionPerformed

    private void afterLoginOwnerSaveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerSaveChangesButtonActionPerformed
        // TODO add your handling code here:
        boolean valid = checkEditPossibility();
        
        if(!valid)
        {
            if(this.afterLoginOwnerLanguageBox.getSelectedIndex() == 0)
            {
                this.afterLoginOwnerErrorLabel.setText("POR FAVOR VERIFIQUE QUE TODOS OS CAMPOS ESTÃO PREENCHIDOS");
            }
            else
            {
                this.afterLoginOwnerErrorLabel.setText("PLEASE CHECK IF EVERY FIELD IS FILLED");
            }
        }
        else
        {
            this.p.setDescription(afterLoginOwnerDescriptionTextArea.getText());
            this.p.getDiscount().setPercentage(Integer.parseInt(afterLoginOwnerDiscountTextField.getText()));
            this.p.setPropertyType((PropertyType) afterLoginOwnerTypeBox.getSelectedItem());
            this.map.put(this.p, (County) this.afterLoginOwnerLocationBox.getSelectedItem());
            
            try
            {
                this.p.setPricePerNight(Integer.parseInt(afterLoginOwnerPriceTextField.getText()));
            }
            catch(NumberFormatException e)
            {
                this.p.setPricePerNight(this.p.getPricePerNight());
            }
                
            
            this.p.getCharacteristics().setMinClients((int) afterLoginOwnerNMinClientsSpinner.getValue());
            this.p.getCharacteristics().setMaxClients((int) afterLoginOwnerNMaxClientsSpinner.getValue());
            this.p.getCharacteristics().setRoomsQuantity((int) afterLoginOwnerNRoomsSpinner.getValue());
            this.p.getCharacteristics().setBathroomQuantity((int) afterLoginOwnerNBathroomsSpinner.getValue());
            this.p.getCharacteristics().setPool(this.afterLoginOwnerPoolCheckBox.isSelected());
            this.p.getCharacteristics().setPets(this.afterLoginOwnerPetsCheckBox.isSelected());
            this.p.getCharacteristics().setKitchen(this.afterLoginOwnerKitchenCheckBox.isSelected());
            this.p.getCharacteristics().setBreakfast(this.afterLoginOwnerBreakfastCheckBox.isSelected());
            this.p.getCharacteristics().setWashingMachine(this.afterLoginOwnerWashingMachineCheckBox.isSelected());
            this.p.getCharacteristics().setWifi(this.afterLoginOwnerWifiCheckBox.isSelected());
            this.p.setName(this.afterLoginOwnerNameField.getText());
            
            
        }
    }//GEN-LAST:event_afterLoginOwnerSaveChangesButtonActionPerformed

    private void afterLoginOwnerAddPropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerAddPropertyButtonActionPerformed
        // TODO add your handling code here:
        this.jpap = new JPAddProperty(this.frame, this.owner, this.afterLoginOwnerLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpap);
    }//GEN-LAST:event_afterLoginOwnerAddPropertyButtonActionPerformed

    private void afterLoginOwnerMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerMessageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afterLoginOwnerMessageButtonActionPerformed

    private void afterLoginOwnerNickLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afterLoginOwnerNickLabelMouseClicked
        // TODO add your handling code here:
        this.jpprof = new JPProfile(this.frame, this.owner, this.afterLoginOwnerLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpprof);
    }//GEN-LAST:event_afterLoginOwnerNickLabelMouseClicked

    private void afterLoginOwnerBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerBookingButtonActionPerformed
        // TODO add your handling code here:
        this.jpcb = new JPConfirmBooking(this.frame, this.owner, this.afterLoginOwnerLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpcb);
    }//GEN-LAST:event_afterLoginOwnerBookingButtonActionPerformed

    private void afterLoginOwnerNickLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_afterLoginOwnerNickLabelPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_afterLoginOwnerNickLabelPropertyChange

    private void afterLoginOwnerNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerNextButtonActionPerformed
        // TODO add your handling code here:
        if(this.position<this.count-1){
            position++;
           this.p = Repository.getRepo().currentProperty(this.map,this.position);   
           this.writeData(p);
           
           if(this.position == this.count - 1)
           {
               this.afterLoginOwnerNextButton.setEnabled(false);
           }
           
           if(this.position == 1)
           {
               this.afterLoginOwnerPreviousButton.setEnabled(true);
           }
        }
    }//GEN-LAST:event_afterLoginOwnerNextButtonActionPerformed

    private void afterLoginOwnerCancelChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerCancelChangesButtonActionPerformed
        // TODO add your handling code here:
        this.writeData(this.p);
    }//GEN-LAST:event_afterLoginOwnerCancelChangesButtonActionPerformed

    private void afterLoginOwnerDeletePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterLoginOwnerDeletePropertyButtonActionPerformed
        // TODO add your handling code here:
        this.p.setClosed(true);
    }//GEN-LAST:event_afterLoginOwnerDeletePropertyButtonActionPerformed

    private void afterLoginOwnerPriceTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_afterLoginOwnerPriceTextFieldFocusLost
        // TODO add your handling code here:
        double price = 0.0;
        
        try
        {
            price = Double.parseDouble(afterLoginOwnerPriceTextField.getText());
        }
        catch(NumberFormatException e)
        {
            afterLoginOwnerPriceTextField.setText(String.valueOf(this.p.getPricePerNight()));
        }
        
        if(price < 0)
        {
            afterLoginOwnerPriceTextField.setText(String.valueOf(price * (-1)));
        }
    }//GEN-LAST:event_afterLoginOwnerPriceTextFieldFocusLost

    private void afterLoginOwnerDiscountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_afterLoginOwnerDiscountTextFieldFocusLost
        // TODO add your handling code here:
        int discount = 0;
        
        try
        {
            discount = Integer.parseInt(afterLoginOwnerDiscountTextField.getText());
        }
        catch(NumberFormatException e)
        {
            afterLoginOwnerDiscountTextField.setText(String.valueOf(this.p.getDiscount().getPercentage()));
        }
        
        if(discount < 0)
        {
            afterLoginOwnerDiscountTextField.setText(String.valueOf(discount * (-1)));
        }
        
        if(discount>100)
        {
            afterLoginOwnerDiscountTextField.setText("100");
        }
    }//GEN-LAST:event_afterLoginOwnerDiscountTextFieldFocusLost

    
    private boolean checkEditPossibility() {
        boolean canEdit = true;
        
        if(this.afterLoginOwnerLocationBox.getSelectedIndex()==0)
        {
            return false;
        }
        
        if(this.afterLoginOwnerDescriptionTextArea.getText().isEmpty())
        {
            return false;
        }
        
        if(this.afterLoginOwnerDiscountTextField.getText().isEmpty())
        {
            return false;
        }
        
        if(this.afterLoginOwnerPriceTextField.getText().isEmpty())
        {
            return false;
        }
        
        return canEdit;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afterLoginOwnerAddPropertyButton;
    private javax.swing.JButton afterLoginOwnerBookingButton;
    private javax.swing.JCheckBox afterLoginOwnerBreakfastCheckBox;
    private javax.swing.JButton afterLoginOwnerCancelChangesButton;
    private javax.swing.JLabel afterLoginOwnerCoinTypeLabel;
    private javax.swing.JButton afterLoginOwnerDeletePropertyButton;
    private javax.swing.JTextArea afterLoginOwnerDescriptionTextArea;
    private javax.swing.JLabel afterLoginOwnerDiscountLabel;
    private javax.swing.JTextField afterLoginOwnerDiscountTextField;
    private javax.swing.JLabel afterLoginOwnerErrorLabel;
    private javax.swing.JPanel afterLoginOwnerErrorPanel;
    private javax.swing.JPanel afterLoginOwnerExtraSearchInfoPanel;
    private javax.swing.JCheckBox afterLoginOwnerExtrasCheckBox;
    private javax.swing.JPanel afterLoginOwnerInfoExtraInfoPanel;
    private javax.swing.JPanel afterLoginOwnerInfoPanel;
    private javax.swing.JPanel afterLoginOwnerInformationPanel;
    private javax.swing.JCheckBox afterLoginOwnerKitchenCheckBox;
    private javax.swing.JComboBox<String> afterLoginOwnerLanguageBox;
    private javax.swing.JComboBox<String> afterLoginOwnerLocationBox;
    private javax.swing.JButton afterLoginOwnerMessageButton;
    private javax.swing.JSpinner afterLoginOwnerNBathroomsSpinner;
    private javax.swing.JLabel afterLoginOwnerNBathroomssLabel;
    private javax.swing.JLabel afterLoginOwnerNBedsLabel;
    private javax.swing.JSpinner afterLoginOwnerNBedsSpinner;
    private javax.swing.JLabel afterLoginOwnerNMaxClientsLabel;
    private javax.swing.JSpinner afterLoginOwnerNMaxClientsSpinner;
    private javax.swing.JLabel afterLoginOwnerNMinClientsLabel;
    private javax.swing.JSpinner afterLoginOwnerNMinClientsSpinner;
    private javax.swing.JLabel afterLoginOwnerNRoomsLabel;
    private javax.swing.JSpinner afterLoginOwnerNRoomsSpinner;
    private javax.swing.JTextField afterLoginOwnerNameField;
    private javax.swing.JButton afterLoginOwnerNextButton;
    private javax.swing.JLabel afterLoginOwnerNickLabel;
    private javax.swing.JPanel afterLoginOwnerPanel;
    private javax.swing.JLabel afterLoginOwnerPercentageLabel;
    private javax.swing.JCheckBox afterLoginOwnerPetsCheckBox;
    private javax.swing.JTextField afterLoginOwnerPhotos;
    private javax.swing.JLabel afterLoginOwnerPontuationLabel;
    private javax.swing.JCheckBox afterLoginOwnerPoolCheckBox;
    private javax.swing.JButton afterLoginOwnerPreviousButton;
    private javax.swing.JTextField afterLoginOwnerPriceTextField;
    private javax.swing.JList<String> afterLoginOwnerRating;
    private javax.swing.JButton afterLoginOwnerSaveChangesButton;
    private java.awt.Label afterLoginOwnerScoreLabel;
    private javax.swing.JPanel afterLoginOwnerTitlePanel;
    private javax.swing.JPanel afterLoginOwnerTopBarPanel;
    private javax.swing.JComboBox<String> afterLoginOwnerTypeBox;
    private javax.swing.JCheckBox afterLoginOwnerWashingMachineCheckBox;
    private javax.swing.JCheckBox afterLoginOwnerWifiCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
