/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import java.util.Date;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;
import projectoalojamento.Repository;
import property.Property;
import property.PropertyType;
import property.booking.Booking;
import property.booking.PaymentType;
import property.location.County;
import user.Client;

/**
 *
 * @author Gustavo Vieira
 */
public class JPBooking extends javax.swing.JPanel {

    private Application frame;
    private JPPropertySearchInfo jppsi;
    private JPProfile jpp;
    private Client client;
    private Property p;
    private PropertyType propertyType;
    private County county;
    private Date starting;
    private Date ending;
    private int nClients;
    private Map<Property, County> map;
    
    /**
     * Creates new form JPBooking
     */
    public JPBooking(Application frame, Client client, Map<Property, County> map, Property p, County county, PropertyType propertyType, int nClients, Date starting, Date ending, Object language) {
        initComponents();
        this.frame = frame;
        this.frame.setSize(700, 584);
        this.client = client;
        this.map = map;
        this.p = p;
        this.propertyType = propertyType;
        this.county = county;
        this.starting = starting;
        this.nClients = nClients;
        this.ending = ending;
        this.bookingLanguageBox.setSelectedItem(language);
        
        this.setInfo();
        
        bookingStartingDatePicker.getMonthView().setLowerBound(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookingPanel = new javax.swing.JPanel();
        bookingTopBarPanel = new javax.swing.JPanel();
        bookingLanguageBox = new javax.swing.JComboBox();
        bookingNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bookingLogoPanel = new javax.swing.JPanel();
        bookingInfoPanel = new javax.swing.JPanel();
        bookingInfoDateClientsPanel = new javax.swing.JPanel();
        bookingStartingDatePicker = new org.jdesktop.swingx.JXDatePicker();
        bookingEndingDatePicker = new org.jdesktop.swingx.JXDatePicker();
        bookingNClientsSpinner = new javax.swing.JSpinner();
        bookingInfoDataPanel = new javax.swing.JPanel();
        bookingPricePerNightField = new javax.swing.JTextField();
        bookingFinalPriceField = new javax.swing.JTextField();
        bookingPaymentTypeBox = new javax.swing.JComboBox();
        bookingNightNumberSlider = new javax.swing.JSlider();
        bookingNightNumberField = new javax.swing.JTextField();
        bookingInfoPropertyPanel = new javax.swing.JPanel();
        bookingInfoPropertyCharacteristicsPanel = new javax.swing.JPanel();
        bookingMinClientsField = new javax.swing.JTextField();
        bookingMaxClientsField = new javax.swing.JTextField();
        bookingNRoomsField = new javax.swing.JTextField();
        bookingNBathroomsField = new javax.swing.JTextField();
        bookingNBedsField = new javax.swing.JTextField();
        bookingMinClientsLabel = new javax.swing.JLabel();
        bookingMaxClientsLabel = new javax.swing.JLabel();
        bookingNRoomsLabel = new javax.swing.JLabel();
        bookingNBathroomsLabel = new javax.swing.JLabel();
        bookingNBedsLabel = new javax.swing.JLabel();
        bookingPropertyTypeField = new javax.swing.JTextField();
        bookingRatingField = new javax.swing.JTextField();
        bookingExtraInfoLeftPanel = new javax.swing.JPanel();
        bookingExtraCheckBox = new javax.swing.JCheckBox();
        bookingPetsCheckBox = new javax.swing.JCheckBox();
        bookingBreakfastCheckBox = new javax.swing.JCheckBox();
        bookingWifiCheckBox = new javax.swing.JCheckBox();
        bookingExtraInfoRightPanel = new javax.swing.JPanel();
        bookingRatingCheckBox = new javax.swing.JCheckBox();
        bookingKitchenCheckBox = new javax.swing.JCheckBox();
        bookingWashingMachineCheckBox = new javax.swing.JCheckBox();
        bookingPoolCheckBox = new javax.swing.JCheckBox();
        bookingDiscountField = new javax.swing.JTextField();
        bookingInfoButtonPanel = new javax.swing.JPanel();
        bookingButton = new javax.swing.JButton();
        bookingBackButton = new javax.swing.JButton();

        bookingLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));

        bookingNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookingNameLabel.setText("Gustavo Moreira Vieira");
        bookingNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingNameLabelMouseClicked(evt);
            }
        });

        jButton1.setText("Mensagens");

        jButton2.setText("Tickets");

        javax.swing.GroupLayout bookingTopBarPanelLayout = new javax.swing.GroupLayout(bookingTopBarPanel);
        bookingTopBarPanel.setLayout(bookingTopBarPanelLayout);
        bookingTopBarPanelLayout.setHorizontalGroup(
            bookingTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingNameLabel)
                .addContainerGap())
        );
        bookingTopBarPanelLayout.setVerticalGroup(
            bookingTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingNameLabel)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bookingLogoPanelLayout = new javax.swing.GroupLayout(bookingLogoPanel);
        bookingLogoPanel.setLayout(bookingLogoPanelLayout);
        bookingLogoPanelLayout.setHorizontalGroup(
            bookingLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bookingLogoPanelLayout.setVerticalGroup(
            bookingLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bookingStartingDatePicker.setToolTipText("Data de Entrada");
        bookingStartingDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingStartingDatePickerActionPerformed(evt);
            }
        });

        bookingEndingDatePicker.setToolTipText("Data de Saída");
        bookingEndingDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingEndingDatePickerActionPerformed(evt);
            }
        });

        bookingNClientsSpinner.setToolTipText("Número de Viajantes");

        javax.swing.GroupLayout bookingInfoDateClientsPanelLayout = new javax.swing.GroupLayout(bookingInfoDateClientsPanel);
        bookingInfoDateClientsPanel.setLayout(bookingInfoDateClientsPanelLayout);
        bookingInfoDateClientsPanelLayout.setHorizontalGroup(
            bookingInfoDateClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoDateClientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingStartingDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingEndingDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingNClientsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        bookingInfoDateClientsPanelLayout.setVerticalGroup(
            bookingInfoDateClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoDateClientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingInfoDateClientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookingStartingDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bookingEndingDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingNClientsSpinner))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bookingPricePerNightField.setEditable(false);
        bookingPricePerNightField.setText("120,000.00€ por noite");

        bookingFinalPriceField.setEditable(false);
        bookingFinalPriceField.setText("120");

        bookingPaymentTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de Pagamento" }));
        bookingPaymentTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingPaymentTypeBoxActionPerformed(evt);
            }
        });

        bookingNightNumberSlider.setMinimum(1);
        bookingNightNumberSlider.setValue(1);
        bookingNightNumberSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bookingNightNumberSliderStateChanged(evt);
            }
        });
        bookingNightNumberSlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bookingNightNumberSliderPropertyChange(evt);
            }
        });

        bookingNightNumberField.setEditable(false);
        bookingNightNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingNightNumberField.setText("1 Noite");

        javax.swing.GroupLayout bookingInfoDataPanelLayout = new javax.swing.GroupLayout(bookingInfoDataPanel);
        bookingInfoDataPanel.setLayout(bookingInfoDataPanelLayout);
        bookingInfoDataPanelLayout.setHorizontalGroup(
            bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingInfoDataPanelLayout.createSequentialGroup()
                        .addGroup(bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookingPricePerNightField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(bookingFinalPriceField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookingNightNumberSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookingNightNumberField)))
                    .addComponent(bookingPaymentTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        bookingInfoDataPanelLayout.setVerticalGroup(
            bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoDataPanelLayout.createSequentialGroup()
                .addGroup(bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingPricePerNightField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingNightNumberSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookingFinalPriceField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bookingNightNumberField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingPaymentTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bookingInfoPropertyCharacteristicsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Características do Alojamento"));

        bookingMinClientsField.setEditable(false);
        bookingMinClientsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingMinClientsField.setText("1");

        bookingMaxClientsField.setEditable(false);
        bookingMaxClientsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingMaxClientsField.setText("5");

        bookingNRoomsField.setEditable(false);
        bookingNRoomsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingNRoomsField.setText("3");

        bookingNBathroomsField.setEditable(false);
        bookingNBathroomsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingNBathroomsField.setText("7");

        bookingNBedsField.setEditable(false);
        bookingNBedsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingNBedsField.setText("5");

        bookingMinClientsLabel.setText("Nº Viajantes Mínimo");

        bookingMaxClientsLabel.setText("Nº Viajantes Máximo");

        bookingNRoomsLabel.setText("Nº Quartos");

        bookingNBathroomsLabel.setText("Nº Quartos de Banho");

        bookingNBedsLabel.setText("Nº Camas");

        bookingPropertyTypeField.setEditable(false);
        bookingPropertyTypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingPropertyTypeField.setText("Tipo de Alojamento");

        bookingRatingField.setEditable(false);
        bookingRatingField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingRatingField.setText("7.9");
        bookingRatingField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        bookingExtraCheckBox.setSelected(true);
        bookingExtraCheckBox.setText("Extras");
        bookingExtraCheckBox.setEnabled(false);

        bookingPetsCheckBox.setText("Animais de Estimação");
        bookingPetsCheckBox.setEnabled(false);

        bookingBreakfastCheckBox.setSelected(true);
        bookingBreakfastCheckBox.setText("Pequeno Almoço");
        bookingBreakfastCheckBox.setEnabled(false);

        bookingWifiCheckBox.setText("Wi-fi");
        bookingWifiCheckBox.setEnabled(false);

        javax.swing.GroupLayout bookingExtraInfoLeftPanelLayout = new javax.swing.GroupLayout(bookingExtraInfoLeftPanel);
        bookingExtraInfoLeftPanel.setLayout(bookingExtraInfoLeftPanelLayout);
        bookingExtraInfoLeftPanelLayout.setHorizontalGroup(
            bookingExtraInfoLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingExtraInfoLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingExtraInfoLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingBreakfastCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingPetsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(bookingExtraCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingWifiCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bookingExtraInfoLeftPanelLayout.setVerticalGroup(
            bookingExtraInfoLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingExtraInfoLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingExtraCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingPetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingBreakfastCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addComponent(bookingWifiCheckBox))
        );

        bookingRatingCheckBox.setSelected(true);
        bookingRatingCheckBox.setText("Avaliações");
        bookingRatingCheckBox.setEnabled(false);

        bookingKitchenCheckBox.setText("Cozinha");
        bookingKitchenCheckBox.setEnabled(false);

        bookingWashingMachineCheckBox.setText("Máquina de Lavar");
        bookingWashingMachineCheckBox.setEnabled(false);

        bookingPoolCheckBox.setSelected(true);
        bookingPoolCheckBox.setText("Piscina");
        bookingPoolCheckBox.setEnabled(false);

        javax.swing.GroupLayout bookingExtraInfoRightPanelLayout = new javax.swing.GroupLayout(bookingExtraInfoRightPanel);
        bookingExtraInfoRightPanel.setLayout(bookingExtraInfoRightPanelLayout);
        bookingExtraInfoRightPanelLayout.setHorizontalGroup(
            bookingExtraInfoRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingExtraInfoRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingExtraInfoRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingWashingMachineCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(bookingKitchenCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingRatingCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingPoolCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bookingExtraInfoRightPanelLayout.setVerticalGroup(
            bookingExtraInfoRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingExtraInfoRightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingRatingCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingKitchenCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingWashingMachineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addComponent(bookingPoolCheckBox))
        );

        bookingDiscountField.setEditable(false);
        bookingDiscountField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bookingDiscountField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookingDiscountField.setText("Contém Desconto");
        bookingDiscountField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout bookingInfoPropertyCharacteristicsPanelLayout = new javax.swing.GroupLayout(bookingInfoPropertyCharacteristicsPanel);
        bookingInfoPropertyCharacteristicsPanel.setLayout(bookingInfoPropertyCharacteristicsPanelLayout);
        bookingInfoPropertyCharacteristicsPanelLayout.setHorizontalGroup(
            bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookingMinClientsField)
                    .addComponent(bookingMaxClientsField)
                    .addComponent(bookingNRoomsField)
                    .addComponent(bookingNBathroomsField)
                    .addComponent(bookingNBedsField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingMinClientsLabel)
                    .addComponent(bookingMaxClientsLabel)
                    .addComponent(bookingNRoomsLabel)
                    .addComponent(bookingNBathroomsLabel)
                    .addComponent(bookingNBedsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createSequentialGroup()
                        .addComponent(bookingExtraInfoLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingExtraInfoRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createSequentialGroup()
                        .addComponent(bookingPropertyTypeField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingRatingField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bookingDiscountField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        bookingInfoPropertyCharacteristicsPanelLayout.setVerticalGroup(
            bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bookingMinClientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bookingMinClientsLabel))
                    .addComponent(bookingRatingField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookingPropertyTypeField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bookingMaxClientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bookingMaxClientsLabel))
                    .addComponent(bookingDiscountField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createSequentialGroup()
                        .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingNRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingNRoomsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingNBathroomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingNBathroomsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookingInfoPropertyCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookingNBedsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingNBedsLabel)))
                    .addComponent(bookingExtraInfoLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingExtraInfoRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bookingButton.setText("Reservar");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        bookingBackButton.setText("Voltar");
        bookingBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookingInfoButtonPanelLayout = new javax.swing.GroupLayout(bookingInfoButtonPanel);
        bookingInfoButtonPanel.setLayout(bookingInfoButtonPanelLayout);
        bookingInfoButtonPanelLayout.setHorizontalGroup(
            bookingInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookingBackButton)
                .addContainerGap())
        );
        bookingInfoButtonPanelLayout.setVerticalGroup(
            bookingInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookingInfoButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bookingInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingButton)
                    .addComponent(bookingBackButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout bookingInfoPropertyPanelLayout = new javax.swing.GroupLayout(bookingInfoPropertyPanel);
        bookingInfoPropertyPanel.setLayout(bookingInfoPropertyPanelLayout);
        bookingInfoPropertyPanelLayout.setHorizontalGroup(
            bookingInfoPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoPropertyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingInfoPropertyCharacteristicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(bookingInfoButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookingInfoPropertyPanelLayout.setVerticalGroup(
            bookingInfoPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoPropertyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingInfoPropertyCharacteristicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(bookingInfoButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bookingInfoPanelLayout = new javax.swing.GroupLayout(bookingInfoPanel);
        bookingInfoPanel.setLayout(bookingInfoPanelLayout);
        bookingInfoPanelLayout.setHorizontalGroup(
            bookingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingInfoDateClientsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingInfoDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingInfoPropertyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookingInfoPanelLayout.setVerticalGroup(
            bookingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingInfoPanelLayout.createSequentialGroup()
                .addComponent(bookingInfoDateClientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingInfoDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingInfoPropertyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bookingPanelLayout = new javax.swing.GroupLayout(bookingPanel);
        bookingPanel.setLayout(bookingPanelLayout);
        bookingPanelLayout.setHorizontalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bookingPanelLayout.setVerticalGroup(
            bookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingPanelLayout.createSequentialGroup()
                .addComponent(bookingTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookingInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookingPaymentTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingPaymentTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingPaymentTypeBoxActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        // TODO add your handling code here:
        double price = 0;
        
        try {
            price = Double.parseDouble(this.bookingFinalPriceField.getText());
        }
        catch(NumberFormatException e)
        {
            price = -1;
        }
        
        if(this.bookingStartingDatePicker.getDate() == null)
        {
            this.bookingStartingDatePicker.setDate(new Date());
            
            if(this.bookingEndingDatePicker.getDate() == null)
            {
                Date d = new Date();
                d.setTime(d.getTime() + 86400000);
                this.bookingEndingDatePicker.setDate(d);
            }
        }
        else
        {
            Date[] dates = { this.bookingStartingDatePicker.getDate() };
            this.bookingEndingDatePicker.getMonthView().setUnselectableDates(dates);
        }
        
        boolean found = Repository.getRepo().canMakeBooking(this.p, this.bookingStartingDatePicker.getDate(), this.bookingEndingDatePicker.getDate());
        
        if(price != -1)
        {
            if(!found)
            {
                Booking b = new Booking((int) this.bookingNClientsSpinner.getValue(), Double.parseDouble(this.bookingFinalPriceField.getText()), this.bookingStartingDatePicker.getDate(), this.bookingEndingDatePicker.getDate(), (PaymentType) this.bookingPaymentTypeBox.getSelectedItem(), this.client);
                this.p.getBookings().add(b);
                Repository.getRepo().getProperties().put(this.p, this.county);
                this.jppsi = new JPPropertySearchInfo(this.frame, this.client, this.map, this.p, this.county, this.propertyType, this.nClients, this.starting, this.ending, this.bookingLanguageBox.getSelectedItem());
                this.frame.changePanel(this.jppsi);
            }
        }
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void bookingBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBackButtonActionPerformed
        // TODO add your handling code here:
        this.jppsi = new JPPropertySearchInfo(this.frame, this.client, this.map, this.p, this.county, this.propertyType, this.nClients, this.starting, this.ending, this.bookingLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jppsi);
    }//GEN-LAST:event_bookingBackButtonActionPerformed

    private void bookingNightNumberSliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bookingNightNumberSliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingNightNumberSliderPropertyChange

    private void bookingStartingDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingStartingDatePickerActionPerformed
        // TODO add your handling code here:
        this.bookingEndingDatePicker.getMonthView().setLowerBound(this.bookingStartingDatePicker.getDate());
        
        if(this.bookingStartingDatePicker.getDate() != null)
        {
            Date[] dates = { this.bookingStartingDatePicker.getDate() };
            this.bookingEndingDatePicker.getMonthView().setUnselectableDates(dates);
        }
        else
        {
            this.bookingStartingDatePicker.setDate(new Date());
        }
        
        this.starting = this.bookingStartingDatePicker.getDate();
    }//GEN-LAST:event_bookingStartingDatePickerActionPerformed

    private void bookingEndingDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingEndingDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingEndingDatePickerActionPerformed

    private void bookingNightNumberSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bookingNightNumberSliderStateChanged
        // TODO add your handling code here:
        if(this.bookingLanguageBox.getSelectedIndex() == 0)
        {
            this.bookingFinalPriceField.setText(String.valueOf(this.p.getPricePerNight() * this.bookingNightNumberSlider.getValue()));
            this.bookingNightNumberField.setText(this.bookingNightNumberSlider.getValue() + " Noites");
        }
        else
        {
            this.bookingPricePerNightField.setText(String.valueOf(this.p.getPricePerNight() * this.bookingNightNumberSlider.getValue()));
            this.bookingNightNumberField.setText(this.bookingNightNumberSlider.getValue() + " Nights");
        }
    }//GEN-LAST:event_bookingNightNumberSliderStateChanged

    private void bookingNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingNameLabelMouseClicked
        // TODO add your handling code here:
        this.jpp = new JPProfile(this.frame, this.client, this.bookingLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpp);
    }//GEN-LAST:event_bookingNameLabelMouseClicked

    private void setInfo() {
        
        this.bookingNClientsSpinner.setModel(new SpinnerNumberModel(this.nClients, p.getCharacteristics().getMinClients(), p.getCharacteristics().getMaxClients(), 1));
        
        this.bookingNameLabel.setText(this.client.getName());
        this.bookingStartingDatePicker.setDate(starting);
        this.bookingEndingDatePicker.setDate(ending);
        this.bookingNClientsSpinner.setValue(this.nClients);
        
        if(this.bookingLanguageBox.getSelectedIndex() == 0)
        {
            this.bookingPricePerNightField.setText(this.p.getPricePerNight() + "€ por noite");
            this.bookingNightNumberField.setText(this.bookingNightNumberSlider.getValue() + " Noites");
        }
        else
        {
            this.bookingPricePerNightField.setText(this.p.getPricePerNight() + "€ per night");
            this.bookingNightNumberField.setText(this.bookingNightNumberSlider.getValue() + " Nights");
        }
        
        this.bookingFinalPriceField.setText(String.valueOf(this.p.getPricePerNight() * this.bookingNightNumberSlider.getValue()));
        this.bookingPaymentTypeBox.setModel(new DefaultComboBoxModel(Repository.getRepo().getPaymentTypes().toArray()));
        
        this.bookingMinClientsField.setText(String.valueOf(this.p.getCharacteristics().getMinClients()));
        this.bookingMaxClientsField.setText(String.valueOf(this.p.getCharacteristics().getMaxClients()));
        this.bookingNRoomsField.setText(String.valueOf(this.p.getCharacteristics().getRoomsQuantity()));
        this.bookingNBathroomsField.setText(String.valueOf(this.p.getCharacteristics().getBathroomQuantity()));
        this.bookingNBedsField.setText(String.valueOf(Repository.getRepo().nBeds(this.p)));
        
        this.bookingPropertyTypeField.setText(this.p.getPropertyType().getName());
        this.bookingRatingField.setText(String.valueOf(this.p.getPropertyRatingMedianPoints()));
        
        if(this.p.getDiscount().getPercentage() > 0)
        {
            this.bookingDiscountField.setVisible(true);
        }
        else
        {
            this.bookingDiscountField.setVisible(false);
        }
        
        if(this.p.getExtras().isEmpty())
        {
            this.bookingExtraCheckBox.setSelected(false);
        }
        else
        {
            this.bookingExtraCheckBox.setSelected(true);
        }
        
        if(this.p.getRatings().isEmpty())
        {
            this.bookingRatingCheckBox.setSelected(false);
        }
        else
        {
            this.bookingRatingCheckBox.setSelected(true);
        }
        
        this.bookingPetsCheckBox.setSelected(this.p.getCharacteristics().isPets());
        this.bookingKitchenCheckBox.setSelected(this.p.getCharacteristics().isKitchen());
        this.bookingBreakfastCheckBox.setSelected(this.p.getCharacteristics().isBreakfast());
        this.bookingWashingMachineCheckBox.setSelected(this.p.getCharacteristics().isWashingMachine());
        this.bookingWifiCheckBox.setSelected(this.p.getCharacteristics().isWifi());
        this.bookingPoolCheckBox.setSelected(this.p.getCharacteristics().isPool());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookingBackButton;
    private javax.swing.JCheckBox bookingBreakfastCheckBox;
    private javax.swing.JButton bookingButton;
    private javax.swing.JTextField bookingDiscountField;
    private org.jdesktop.swingx.JXDatePicker bookingEndingDatePicker;
    private javax.swing.JCheckBox bookingExtraCheckBox;
    private javax.swing.JPanel bookingExtraInfoLeftPanel;
    private javax.swing.JPanel bookingExtraInfoRightPanel;
    private javax.swing.JTextField bookingFinalPriceField;
    private javax.swing.JPanel bookingInfoButtonPanel;
    private javax.swing.JPanel bookingInfoDataPanel;
    private javax.swing.JPanel bookingInfoDateClientsPanel;
    private javax.swing.JPanel bookingInfoPanel;
    private javax.swing.JPanel bookingInfoPropertyCharacteristicsPanel;
    private javax.swing.JPanel bookingInfoPropertyPanel;
    private javax.swing.JCheckBox bookingKitchenCheckBox;
    private javax.swing.JComboBox bookingLanguageBox;
    private javax.swing.JPanel bookingLogoPanel;
    private javax.swing.JTextField bookingMaxClientsField;
    private javax.swing.JLabel bookingMaxClientsLabel;
    private javax.swing.JTextField bookingMinClientsField;
    private javax.swing.JLabel bookingMinClientsLabel;
    private javax.swing.JTextField bookingNBathroomsField;
    private javax.swing.JLabel bookingNBathroomsLabel;
    private javax.swing.JTextField bookingNBedsField;
    private javax.swing.JLabel bookingNBedsLabel;
    private javax.swing.JSpinner bookingNClientsSpinner;
    private javax.swing.JTextField bookingNRoomsField;
    private javax.swing.JLabel bookingNRoomsLabel;
    private javax.swing.JLabel bookingNameLabel;
    private javax.swing.JTextField bookingNightNumberField;
    private javax.swing.JSlider bookingNightNumberSlider;
    private javax.swing.JPanel bookingPanel;
    private javax.swing.JComboBox bookingPaymentTypeBox;
    private javax.swing.JCheckBox bookingPetsCheckBox;
    private javax.swing.JCheckBox bookingPoolCheckBox;
    private javax.swing.JTextField bookingPricePerNightField;
    private javax.swing.JTextField bookingPropertyTypeField;
    private javax.swing.JCheckBox bookingRatingCheckBox;
    private javax.swing.JTextField bookingRatingField;
    private org.jdesktop.swingx.JXDatePicker bookingStartingDatePicker;
    private javax.swing.JPanel bookingTopBarPanel;
    private javax.swing.JCheckBox bookingWashingMachineCheckBox;
    private javax.swing.JCheckBox bookingWifiCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
