/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import projectoalojamento.Repository;
import property.Discount;
import property.Property;
import property.PropertyType;
import property.Rating;
import property.location.County;
import user.Client;

/**
 *
 * @author Gustavo Vieira
 */
public class JPPropertySearch extends javax.swing.JPanel {

    private Application frame;
    private JPPropertySearchInfo jppsi;
    private Client client;
    List<Property> list;
    Property prop = new Property();
    int min = 0;
    int max = 5000;
    
    /**
     * Creates new form JPPropertySearch
     */
    public JPPropertySearch(Application frame, Client client, Object language) {
        initComponents();
        
        this.frame = frame;
        this.frame.setSize(1000,600);
        this.client = client;
        this.propertySearchLanguageBox.setSelectedItem(language);
        this.propertySearchMaxPricePerNightSlider.setMaximum(max);
        this.propertySearchMinPricePerNightSlider.setMinimum(min);
        this.propertySearchMaxPricePerNightField.setText(String.valueOf(propertySearchMaxPricePerNightSlider.getValue()) );
        this.propertySearchMinPricePerNightField.setText(String.valueOf(propertySearchMinPricePerNightSlider.getValue()) );
        
        this.propertySearchPropertyTypeBox.setModel(new DefaultComboBoxModel(Repository.getRepo().getPropertiesTypes().toArray()));
        this.propertySearchLocationBox.setModel(new DefaultComboBoxModel(Repository.getRepo().getCounties().toArray()));
        this.propertySearchList.setListData(Repository.getRepo().getProperties().keySet().toArray());
        
        this.changeTextToSelectedLanguage();
        this.changeButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertySearchPanel = new javax.swing.JPanel();
        propertySearchTopBarPanel = new javax.swing.JPanel();
        propertySearchLanguageBox = new javax.swing.JComboBox();
        propertySearchNameLabel = new javax.swing.JLabel();
        propertySearchMessageButton = new javax.swing.JButton();
        propertySearchTicketButton = new javax.swing.JButton();
        propertySearchRegisterButton = new javax.swing.JButton();
        propertySearchLoginButton = new javax.swing.JButton();
        propertySearchLogoPanel = new javax.swing.JPanel();
        propertySearchInfoPanel = new javax.swing.JPanel();
        propertySearchStartingDatePicker = new org.jdesktop.swingx.JXDatePicker();
        propertySearchEndingDatePicker = new org.jdesktop.swingx.JXDatePicker();
        propertySearchPropertyTypeBox = new javax.swing.JComboBox();
        propertySearchSearchButton = new javax.swing.JButton();
        propertySearchExtraSearchInfoPanel = new javax.swing.JPanel();
        propertySearchNClientsSpinner = new javax.swing.JSpinner();
        propertySearchNRoomsSpinner = new javax.swing.JSpinner();
        propertySearchNBathroomsSpinner = new javax.swing.JSpinner();
        propertySearchNBedsSpinner = new javax.swing.JSpinner();
        propertySearchNClientsLabel = new javax.swing.JLabel();
        propertySearchNRoomsLabel = new javax.swing.JLabel();
        propertySearchNBathroomssLabel = new javax.swing.JLabel();
        propertySearchNBedsLabel = new javax.swing.JLabel();
        propertySearchBedTypeBox = new javax.swing.JComboBox();
        propertySearchMinPricePerNightSlider = new javax.swing.JSlider();
        propertySearchMinPricePerNightField = new javax.swing.JTextField();
        propertySearchMaxPricePerNightSlider = new javax.swing.JSlider();
        propertySearchMaxPricePerNightField = new javax.swing.JTextField();
        propertySearchMinRatingField = new javax.swing.JSpinner();
        propertySearchMinRatingLabel = new javax.swing.JLabel();
        propertySearchInfoExtraInfoPanel = new javax.swing.JPanel();
        propertySearchDiscountsCheckBox = new javax.swing.JCheckBox();
        propertySearchExtrasCheckBox = new javax.swing.JCheckBox();
        propertySearchRatingsCheckBox = new javax.swing.JCheckBox();
        propertySearchPetsCheckBox = new javax.swing.JCheckBox();
        propertySearchKitchenCheckBox = new javax.swing.JCheckBox();
        propertySearchWashingMachineCheckBox = new javax.swing.JCheckBox();
        propertySearchWifiCheckBox = new javax.swing.JCheckBox();
        propertySearchBreakfastCheckBox = new javax.swing.JCheckBox();
        propertySearchPoolCheckBox = new javax.swing.JCheckBox();
        propertySearchLocationBox = new javax.swing.JComboBox();
        propertySearchEndingDateLabel = new javax.swing.JLabel();
        propertySearchStartingDateLabel = new javax.swing.JLabel();
        propertySearchListPanel = new javax.swing.JPanel();
        propertySearchListScrollPane = new javax.swing.JScrollPane();
        propertySearchList = new javax.swing.JList();

        propertySearchLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));
        propertySearchLanguageBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchLanguageBoxPropertyChange(evt);
            }
        });

        propertySearchNameLabel.setText("Gustavo Moreira Vieira");

        propertySearchMessageButton.setText("Mensagens");

        propertySearchTicketButton.setText("Tickets");

        propertySearchRegisterButton.setText("Registo");

        propertySearchLoginButton.setText("Login");

        javax.swing.GroupLayout propertySearchTopBarPanelLayout = new javax.swing.GroupLayout(propertySearchTopBarPanel);
        propertySearchTopBarPanel.setLayout(propertySearchTopBarPanelLayout);
        propertySearchTopBarPanelLayout.setHorizontalGroup(
            propertySearchTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propertySearchLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchRegisterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchTicketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchMessageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchNameLabel)
                .addContainerGap())
        );
        propertySearchTopBarPanelLayout.setVerticalGroup(
            propertySearchTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchNameLabel)
                    .addComponent(propertySearchMessageButton)
                    .addComponent(propertySearchTicketButton)
                    .addComponent(propertySearchRegisterButton)
                    .addComponent(propertySearchLoginButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout propertySearchLogoPanelLayout = new javax.swing.GroupLayout(propertySearchLogoPanel);
        propertySearchLogoPanel.setLayout(propertySearchLogoPanelLayout);
        propertySearchLogoPanelLayout.setHorizontalGroup(
            propertySearchLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        propertySearchLogoPanelLayout.setVerticalGroup(
            propertySearchLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        propertySearchStartingDatePicker.setToolTipText("Dia inicial disponível para reserva");
        propertySearchStartingDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchStartingDatePickerActionPerformed(evt);
            }
        });

        propertySearchEndingDatePicker.setToolTipText("Dia final disponível para reserva");
        propertySearchEndingDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchEndingDatePickerActionPerformed(evt);
            }
        });

        propertySearchPropertyTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de Alojamento" }));

        propertySearchSearchButton.setText("Pesquisar");
        propertySearchSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchSearchButtonActionPerformed(evt);
            }
        });

        propertySearchExtraSearchInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));

        propertySearchNClientsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        propertySearchNClientsSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchNClientsSpinnerPropertyChange(evt);
            }
        });

        propertySearchNRoomsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        propertySearchNRoomsSpinner.setToolTipText("Número mínimo de quartos do alojamento");
        propertySearchNRoomsSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchNRoomsSpinnerPropertyChange(evt);
            }
        });

        propertySearchNBathroomsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        propertySearchNBathroomsSpinner.setToolTipText("Número mínimo de quartos de banho do alojamento");
        propertySearchNBathroomsSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchNBathroomsSpinnerPropertyChange(evt);
            }
        });

        propertySearchNBedsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        propertySearchNBedsSpinner.setToolTipText("Número mínimo de camas do alojamento");
        propertySearchNBedsSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchNBedsSpinnerPropertyChange(evt);
            }
        });

        propertySearchNClientsLabel.setText("Nº Viajantes");

        propertySearchNRoomsLabel.setText("Nº Quartos");

        propertySearchNBathroomssLabel.setText("Nº Quartos de Banho");

        propertySearchNBedsLabel.setText("Nº Camas");

        propertySearchBedTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo de Cama" }));
        propertySearchBedTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchBedTypeBoxActionPerformed(evt);
            }
        });

        propertySearchMinPricePerNightSlider.setMinimum(1);
        propertySearchMinPricePerNightSlider.setValue(1);
        propertySearchMinPricePerNightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                propertySearchMinPricePerNightSliderStateChanged(evt);
            }
        });

        propertySearchMinPricePerNightField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchMinPricePerNightField.setText("120€");

        propertySearchMaxPricePerNightSlider.setMinimum(1);
        propertySearchMaxPricePerNightSlider.setValue(100);
        propertySearchMaxPricePerNightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                propertySearchMaxPricePerNightSliderStateChanged(evt);
            }
        });
        propertySearchMaxPricePerNightSlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchMaxPricePerNightSliderPropertyChange(evt);
            }
        });

        propertySearchMaxPricePerNightField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchMaxPricePerNightField.setText("120,000.00€");
        propertySearchMaxPricePerNightField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchMaxPricePerNightFieldActionPerformed(evt);
            }
        });

        propertySearchMinRatingField.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(1.0f)));
        propertySearchMinRatingField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchMinRatingFieldPropertyChange(evt);
            }
        });

        propertySearchMinRatingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertySearchMinRatingLabel.setText("Avaliação Mínima");

        propertySearchInfoExtraInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));

        propertySearchDiscountsCheckBox.setText("Contém descontos");
        propertySearchDiscountsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchDiscountsCheckBoxActionPerformed(evt);
            }
        });

        propertySearchExtrasCheckBox.setText("Contém extras");
        propertySearchExtrasCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchExtrasCheckBoxActionPerformed(evt);
            }
        });

        propertySearchRatingsCheckBox.setText("Contém avaliações");

        propertySearchPetsCheckBox.setText("Animais de Estimação");
        propertySearchPetsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchPetsCheckBoxActionPerformed(evt);
            }
        });

        propertySearchKitchenCheckBox.setText("Cozinha");
        propertySearchKitchenCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchKitchenCheckBoxActionPerformed(evt);
            }
        });

        propertySearchWashingMachineCheckBox.setText("Máquina de Lavar");
        propertySearchWashingMachineCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchWashingMachineCheckBoxActionPerformed(evt);
            }
        });

        propertySearchWifiCheckBox.setText("Wi-fi");
        propertySearchWifiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchWifiCheckBoxActionPerformed(evt);
            }
        });

        propertySearchBreakfastCheckBox.setText("Pequeno Almoço");
        propertySearchBreakfastCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchBreakfastCheckBoxActionPerformed(evt);
            }
        });

        propertySearchPoolCheckBox.setText("Piscina");
        propertySearchPoolCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchPoolCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propertySearchInfoExtraInfoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoExtraInfoPanel);
        propertySearchInfoExtraInfoPanel.setLayout(propertySearchInfoExtraInfoPanelLayout);
        propertySearchInfoExtraInfoPanelLayout.setHorizontalGroup(
            propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoExtraInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchPetsCheckBox)
                    .addComponent(propertySearchWashingMachineCheckBox)
                    .addGroup(propertySearchInfoExtraInfoPanelLayout.createSequentialGroup()
                        .addGroup(propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(propertySearchDiscountsCheckBox)
                            .addComponent(propertySearchKitchenCheckBox)
                            .addComponent(propertySearchWifiCheckBox))
                        .addGap(16, 16, 16)
                        .addGroup(propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(propertySearchPoolCheckBox)
                            .addComponent(propertySearchBreakfastCheckBox)
                            .addGroup(propertySearchInfoExtraInfoPanelLayout.createSequentialGroup()
                                .addComponent(propertySearchExtrasCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(propertySearchRatingsCheckBox)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        propertySearchInfoExtraInfoPanelLayout.setVerticalGroup(
            propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoExtraInfoPanelLayout.createSequentialGroup()
                .addGroup(propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchDiscountsCheckBox)
                    .addComponent(propertySearchExtrasCheckBox)
                    .addComponent(propertySearchRatingsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchPetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchKitchenCheckBox)
                    .addComponent(propertySearchBreakfastCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchWashingMachineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoExtraInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchWifiCheckBox)
                    .addComponent(propertySearchPoolCheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout propertySearchExtraSearchInfoPanelLayout = new javax.swing.GroupLayout(propertySearchExtraSearchInfoPanel);
        propertySearchExtraSearchInfoPanel.setLayout(propertySearchExtraSearchInfoPanelLayout);
        propertySearchExtraSearchInfoPanelLayout.setHorizontalGroup(
            propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchExtraSearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchNClientsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(propertySearchNRoomsSpinner)
                    .addComponent(propertySearchNBathroomsSpinner)
                    .addComponent(propertySearchNBedsSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchNBedsLabel)
                    .addComponent(propertySearchNBathroomssLabel)
                    .addComponent(propertySearchNRoomsLabel)
                    .addComponent(propertySearchNClientsLabel))
                .addGap(44, 44, 44)
                .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(propertySearchExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addComponent(propertySearchMinPricePerNightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchMinPricePerNightField))
                    .addComponent(propertySearchBedTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(propertySearchExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(propertySearchMaxPricePerNightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(propertySearchMinRatingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(propertySearchMaxPricePerNightField)
                            .addComponent(propertySearchMinRatingField))))
                .addGap(18, 18, 18)
                .addComponent(propertySearchInfoExtraInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        propertySearchExtraSearchInfoPanelLayout.setVerticalGroup(
            propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchExtraSearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(propertySearchInfoExtraInfoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(propertySearchExtraSearchInfoPanelLayout.createSequentialGroup()
                        .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertySearchNClientsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertySearchNClientsLabel))
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertySearchMinRatingField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertySearchMinRatingLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertySearchNRoomsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertySearchNRoomsLabel))
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(propertySearchMaxPricePerNightField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(propertySearchMaxPricePerNightSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertySearchNBathroomsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertySearchNBathroomssLabel))
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(propertySearchMinPricePerNightField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(propertySearchMinPricePerNightSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(propertySearchExtraSearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(propertySearchNBedsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(propertySearchNBedsLabel))
                            .addComponent(propertySearchBedTypeBox))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        propertySearchLocationBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Localidade" }));

        propertySearchEndingDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertySearchEndingDateLabel.setText("Data Final");

        propertySearchStartingDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propertySearchStartingDateLabel.setText("Data Inicial");

        javax.swing.GroupLayout propertySearchInfoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoPanel);
        propertySearchInfoPanel.setLayout(propertySearchInfoPanelLayout);
        propertySearchInfoPanelLayout.setHorizontalGroup(
            propertySearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchExtraSearchInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(propertySearchInfoPanelLayout.createSequentialGroup()
                        .addComponent(propertySearchLocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchStartingDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchStartingDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchEndingDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchEndingDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchPropertyTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        propertySearchInfoPanelLayout.setVerticalGroup(
            propertySearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(propertySearchPropertyTypeBox)
                    .addComponent(propertySearchLocationBox)
                    .addComponent(propertySearchStartingDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchStartingDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchEndingDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchEndingDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchExtraSearchInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        propertySearchList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        propertySearchList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertySearchListMouseClicked(evt);
            }
        });
        propertySearchList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchListPropertyChange(evt);
            }
        });
        propertySearchListScrollPane.setViewportView(propertySearchList);

        javax.swing.GroupLayout propertySearchListPanelLayout = new javax.swing.GroupLayout(propertySearchListPanel);
        propertySearchListPanel.setLayout(propertySearchListPanelLayout);
        propertySearchListPanelLayout.setHorizontalGroup(
            propertySearchListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchListScrollPane)
                .addContainerGap())
        );
        propertySearchListPanelLayout.setVerticalGroup(
            propertySearchListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchListPanelLayout.createSequentialGroup()
                .addComponent(propertySearchListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout propertySearchPanelLayout = new javax.swing.GroupLayout(propertySearchPanel);
        propertySearchPanel.setLayout(propertySearchPanelLayout);
        propertySearchPanelLayout.setHorizontalGroup(
            propertySearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        propertySearchPanelLayout.setVerticalGroup(
            propertySearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchPanelLayout.createSequentialGroup()
                .addComponent(propertySearchTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void propertySearchMaxPricePerNightFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchMaxPricePerNightFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertySearchMaxPricePerNightFieldActionPerformed

    private void propertySearchListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertySearchListMouseClicked
        // TODO add your handling code here:
        JList list = (JList)evt.getSource();
        
        if(evt.getClickCount() == 2)
        {
            if(list.getModel().getSize() != 0)
            {
                this.jppsi = new JPPropertySearchInfo(this.frame, this.client, this.list, (Property) this.propertySearchList.getSelectedValue(), this.propertySearchLanguageBox.getSelectedItem());
                this.frame.changePanel(this.jppsi);
            }
        }
        
    }//GEN-LAST:event_propertySearchListMouseClicked

    private void propertySearchPoolCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchPoolCheckBoxActionPerformed
        // TODO add your handling code here:
        
        if (propertySearchPoolCheckBox.isEnabled()== true)
        {
            prop.getCharacteristics().setPool(true);
        }
        else
        {
            prop.getCharacteristics().setPool(false);
        }
    }//GEN-LAST:event_propertySearchPoolCheckBoxActionPerformed

    private void propertySearchStartingDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchStartingDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertySearchStartingDatePickerActionPerformed

    private void propertySearchEndingDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchEndingDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propertySearchEndingDatePickerActionPerformed

    private void propertySearchKitchenCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchKitchenCheckBoxActionPerformed
        // TODO add your handling code here:
        if (propertySearchKitchenCheckBox.isEnabled()== true)
        {
            prop.getCharacteristics().setKitchen(true);
        }
        else
        {
            prop.getCharacteristics().setKitchen(false);
        }
    }//GEN-LAST:event_propertySearchKitchenCheckBoxActionPerformed

    private void propertySearchListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchListPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_propertySearchListPropertyChange

    private void propertySearchNClientsSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchNClientsSpinnerPropertyChange
        // TODO add your handling code here:
        prop.getCharacteristics().setMinClients((int) propertySearchNClientsSpinner.getValue());
    }//GEN-LAST:event_propertySearchNClientsSpinnerPropertyChange

    private void propertySearchNRoomsSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchNRoomsSpinnerPropertyChange
        // TODO add your handling code here:
        prop.getCharacteristics().setRoomsQuantity((int) propertySearchNRoomsSpinner.getValue());
    }//GEN-LAST:event_propertySearchNRoomsSpinnerPropertyChange

    private void propertySearchNBathroomsSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchNBathroomsSpinnerPropertyChange
        // TODO add your handling code here:
        prop.getCharacteristics().setBathroomQuantity((int) propertySearchNBathroomsSpinner.getValue());
    }//GEN-LAST:event_propertySearchNBathroomsSpinnerPropertyChange

    private void propertySearchNBedsSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchNBedsSpinnerPropertyChange
        // TODO add your handling code here:
        prop.getCharacteristics().setRoomsQuantity((int) propertySearchNBedsSpinner.getValue());
    }//GEN-LAST:event_propertySearchNBedsSpinnerPropertyChange

    private void propertySearchMinRatingFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchMinRatingFieldPropertyChange
        // TODO add your handling code here:   
    }//GEN-LAST:event_propertySearchMinRatingFieldPropertyChange

    private void propertySearchMaxPricePerNightSliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchMaxPricePerNightSliderPropertyChange
        // TODO add your handling code here:   
    }//GEN-LAST:event_propertySearchMaxPricePerNightSliderPropertyChange

    private void propertySearchMaxPricePerNightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_propertySearchMaxPricePerNightSliderStateChanged
        // TODO add your handling code here:
        this.propertySearchMaxPricePerNightField.setText(String.valueOf(propertySearchMaxPricePerNightSlider.getValue()) );
        this.propertySearchMinPricePerNightSlider.setMaximum(this.propertySearchMaxPricePerNightSlider.getValue());
    }//GEN-LAST:event_propertySearchMaxPricePerNightSliderStateChanged

    private void propertySearchMinPricePerNightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_propertySearchMinPricePerNightSliderStateChanged
        // TODO add your handling code here:
        this.propertySearchMinPricePerNightField.setText(String.valueOf(propertySearchMinPricePerNightSlider.getValue()));
        this.propertySearchMaxPricePerNightSlider.setMinimum(this.propertySearchMinPricePerNightSlider.getValue());
    }//GEN-LAST:event_propertySearchMinPricePerNightSliderStateChanged

    private void propertySearchBedTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchBedTypeBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_propertySearchBedTypeBoxActionPerformed

    private void propertySearchDiscountsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchDiscountsCheckBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_propertySearchDiscountsCheckBoxActionPerformed

    private void propertySearchPetsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchPetsCheckBoxActionPerformed
        // TODO add your handling code here:
        if (propertySearchPetsCheckBox.isEnabled()== true)
        {
            prop.getCharacteristics().setPets(true);
        }
        else
        {
            prop.getCharacteristics().setPets(false);
        }
    }//GEN-LAST:event_propertySearchPetsCheckBoxActionPerformed

    private void propertySearchWashingMachineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchWashingMachineCheckBoxActionPerformed
        // TODO add your handling code here:
        if (propertySearchWashingMachineCheckBox.isEnabled()== true)
        {
            prop.getCharacteristics().setWashingMachine(true);
        }
        else
        {
            prop.getCharacteristics().setWashingMachine(false);
        }
    }//GEN-LAST:event_propertySearchWashingMachineCheckBoxActionPerformed

    private void propertySearchWifiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchWifiCheckBoxActionPerformed
        // TODO add your handling code here:
        if (propertySearchWifiCheckBox.isEnabled()== true)
        {
            prop.getCharacteristics().setWifi(true);
        }
        else
        {
            prop.getCharacteristics().setWifi(false && true);
        }
    }//GEN-LAST:event_propertySearchWifiCheckBoxActionPerformed

    private void propertySearchExtrasCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchExtrasCheckBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_propertySearchExtrasCheckBoxActionPerformed

    private void propertySearchBreakfastCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchBreakfastCheckBoxActionPerformed
        // TODO add your handling code here:
        if (propertySearchBreakfastCheckBox.isEnabled()== true)
        {
            prop.getCharacteristics().setBreakfast(true);
        }
        else
        {
            prop.getCharacteristics().setBreakfast(false);
        }
    }//GEN-LAST:event_propertySearchBreakfastCheckBoxActionPerformed

    private void propertySearchLanguageBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchLanguageBoxPropertyChange
        // TODO add your handling code here:
        this.changeTextToSelectedLanguage();
    }//GEN-LAST:event_propertySearchLanguageBoxPropertyChange

    private void propertySearchSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchSearchButtonActionPerformed
        // TODO add your handling code here:
        
        Property p = new Property();
        p.setPricePerNight((float)this.propertySearchMinPricePerNightSlider.getValue());
        p.getCharacteristics().setMinClients((int) this.propertySearchNClientsSpinner.getValue());
        p.getCharacteristics().setRoomsQuantity((int) this.propertySearchNRoomsSpinner.getValue());
        p.getCharacteristics().setBathroomQuantity((int) this.propertySearchNBathroomsSpinner.getValue());
        
        p.setPropertyType((PropertyType) this.propertySearchPropertyTypeBox.getSelectedItem());
        
        p.getCharacteristics().setPets(this.propertySearchPetsCheckBox.isSelected());
        p.getCharacteristics().setKitchen(this.propertySearchKitchenCheckBox.isSelected());
        p.getCharacteristics().setBreakfast(this.propertySearchBreakfastCheckBox.isSelected());
        p.getCharacteristics().setWashingMachine(this.propertySearchWashingMachineCheckBox.isSelected());
        p.getCharacteristics().setWifi(this.propertySearchWifiCheckBox.isSelected());
        p.getCharacteristics().setPool(this.propertySearchPoolCheckBox.isSelected());
        
        Discount d = new Discount();
        
        if(this.propertySearchDiscountsCheckBox.isSelected())
        {
            d.setPercentage(0);
        }
        p.setDiscount(d);
        
        if(this.propertySearchExtrasCheckBox.isSelected())
        {
            p.getExtras().add(new Discount());
        }
        
        Rating r = new Rating();
        r.setPoints((float) this.propertySearchMinRatingField.getValue());
        
        if(this.propertySearchRatingsCheckBox.isSelected())
        {
            p.getRatings().add(r);
        }
        
        Map<Property, County> mp = Repository.getRepo().listProperties(p, (County) this.propertySearchLocationBox.getSelectedItem(), this.propertySearchMaxPricePerNightSlider.getValue());
        
        this.propertySearchList.setListData(mp.keySet().toArray());
    }//GEN-LAST:event_propertySearchSearchButtonActionPerformed

    private void changeButtons() {
        if(this.client.getName().isEmpty())
        {
            this.propertySearchNameLabel.setEnabled(false);
            this.propertySearchNameLabel.setVisible(false);
            this.propertySearchMessageButton.setEnabled(false);
            this.propertySearchMessageButton.setVisible(false);
            this.propertySearchTicketButton.setEnabled(false);
            this.propertySearchTicketButton.setVisible(false);
        }
        else
        {
            this.propertySearchLoginButton.setEnabled(false);
            this.propertySearchLoginButton.setVisible(false);
            this.propertySearchRegisterButton.setEnabled(false);
            this.propertySearchRegisterButton.setVisible(false);
        }
    }
    
    private void changeTextToSelectedLanguage() {
        
        if(this.propertySearchLanguageBox.getSelectedIndex() == 0)
        {
            this.propertySearchSearchButton.setText("Pesquisar");
            this.propertySearchNClientsLabel.setText("Nº Viajantes");
            this.propertySearchNRoomsLabel.setText("Nº Quartos");
            this.propertySearchNBathroomssLabel.setText("Nº Quartos de Banho");
            this.propertySearchNBedsLabel.setText("Nº Camas");
            this.propertySearchMinRatingLabel.setText("Avaliação Mínima");
            this.propertySearchDiscountsCheckBox.setText("Contém descontos");
            this.propertySearchExtrasCheckBox.setText("Contém extras");
            this.propertySearchRatingsCheckBox.setText("Contém avaliações");
            this.propertySearchPetsCheckBox.setText("Animais de Estimação");
            this.propertySearchKitchenCheckBox.setText("Cozinha");
            this.propertySearchBreakfastCheckBox.setText("Pequeno Almoço");
            this.propertySearchWashingMachineCheckBox.setText("Máquina de Lavar");
            this.propertySearchPoolCheckBox.setText("Piscina");
            
            if(this.client.getName().isEmpty())
            {
                this.propertySearchLoginButton.setText("Login");
                this.propertySearchRegisterButton.setText("Registo");
            }
            else
            {
                this.propertySearchMessageButton.setText("Mensagens");
                this.propertySearchTicketButton.setText("Tickets");
            }
        }
        else
        {
            this.propertySearchSearchButton.setText("Search");
            this.propertySearchNClientsLabel.setText("Travelers");
            this.propertySearchNRoomsLabel.setText("Rooms");
            this.propertySearchNBathroomssLabel.setText("Bathrooms");
            this.propertySearchNBedsLabel.setText("Beds");
            this.propertySearchMinRatingLabel.setText("Minimum Rating");
            this.propertySearchDiscountsCheckBox.setText("Contains discounts");
            this.propertySearchExtrasCheckBox.setText("Contains extras");
            this.propertySearchRatingsCheckBox.setText("Contains ratings");
            this.propertySearchPetsCheckBox.setText("Pets");
            this.propertySearchKitchenCheckBox.setText("Kitchen");
            this.propertySearchBreakfastCheckBox.setText("Breakfast");
            this.propertySearchWashingMachineCheckBox.setText("Washing Machine");
            this.propertySearchPoolCheckBox.setText("Pool");
            
            if(this.client.getName().isEmpty())
            {
                this.propertySearchLoginButton.setText("Sign In");
                this.propertySearchRegisterButton.setText("Sign Up");
            }
            else
            {
                this.propertySearchMessageButton.setText("Messages");
                this.propertySearchTicketButton.setText("Tickets");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox propertySearchBedTypeBox;
    private javax.swing.JCheckBox propertySearchBreakfastCheckBox;
    private javax.swing.JCheckBox propertySearchDiscountsCheckBox;
    private javax.swing.JLabel propertySearchEndingDateLabel;
    private org.jdesktop.swingx.JXDatePicker propertySearchEndingDatePicker;
    private javax.swing.JPanel propertySearchExtraSearchInfoPanel;
    private javax.swing.JCheckBox propertySearchExtrasCheckBox;
    private javax.swing.JPanel propertySearchInfoExtraInfoPanel;
    private javax.swing.JPanel propertySearchInfoPanel;
    private javax.swing.JCheckBox propertySearchKitchenCheckBox;
    private javax.swing.JComboBox propertySearchLanguageBox;
    private javax.swing.JList propertySearchList;
    private javax.swing.JPanel propertySearchListPanel;
    private javax.swing.JScrollPane propertySearchListScrollPane;
    private javax.swing.JComboBox propertySearchLocationBox;
    private javax.swing.JButton propertySearchLoginButton;
    private javax.swing.JPanel propertySearchLogoPanel;
    private javax.swing.JTextField propertySearchMaxPricePerNightField;
    private javax.swing.JSlider propertySearchMaxPricePerNightSlider;
    private javax.swing.JButton propertySearchMessageButton;
    private javax.swing.JTextField propertySearchMinPricePerNightField;
    private javax.swing.JSlider propertySearchMinPricePerNightSlider;
    private javax.swing.JSpinner propertySearchMinRatingField;
    private javax.swing.JLabel propertySearchMinRatingLabel;
    private javax.swing.JSpinner propertySearchNBathroomsSpinner;
    private javax.swing.JLabel propertySearchNBathroomssLabel;
    private javax.swing.JLabel propertySearchNBedsLabel;
    private javax.swing.JSpinner propertySearchNBedsSpinner;
    private javax.swing.JLabel propertySearchNClientsLabel;
    private javax.swing.JSpinner propertySearchNClientsSpinner;
    private javax.swing.JLabel propertySearchNRoomsLabel;
    private javax.swing.JSpinner propertySearchNRoomsSpinner;
    private javax.swing.JLabel propertySearchNameLabel;
    private javax.swing.JPanel propertySearchPanel;
    private javax.swing.JCheckBox propertySearchPetsCheckBox;
    private javax.swing.JCheckBox propertySearchPoolCheckBox;
    private javax.swing.JComboBox propertySearchPropertyTypeBox;
    private javax.swing.JCheckBox propertySearchRatingsCheckBox;
    private javax.swing.JButton propertySearchRegisterButton;
    private javax.swing.JButton propertySearchSearchButton;
    private javax.swing.JLabel propertySearchStartingDateLabel;
    private org.jdesktop.swingx.JXDatePicker propertySearchStartingDatePicker;
    private javax.swing.JButton propertySearchTicketButton;
    private javax.swing.JPanel propertySearchTopBarPanel;
    private javax.swing.JCheckBox propertySearchWashingMachineCheckBox;
    private javax.swing.JCheckBox propertySearchWifiCheckBox;
    // End of variables declaration//GEN-END:variables
}
