/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ListModel;
import projectoalojamento.Repository;
import property.Property;
import property.PropertyType;
import property.location.County;
import user.Client;

/**
 *
 * @author Gustavo Vieira
 */
public class JPPropertySearchInfo extends javax.swing.JPanel {

    private Application frame;
    private JPPropertySearch jpps;
    private JPBooking jpb;
    private JPLogin jpl;
    private JPRegister jpr;
    private JPProfile jpp;
    private Client client;
    private Property p;
    private PropertyType propertyType;
    private County county;
    private Date starting;
    private Date ending;
    private int nClients;
    private Map<Property, County> map;
    
    /**
     * Creates new form JPPropertyInfo
     */
    public JPPropertySearchInfo(Application frame, Client client, Map<Property, County> map, Property p, County county, PropertyType propertyType, int nClients, Date starting, Date ending, Object language) {
        initComponents();
        
        this.frame = frame;
        this.frame.setSize(1110, 696);
        this.client = client;
        this.map = map;
        this.p = p;
        this.propertyType = propertyType;
        this.county = county;
        this.starting = starting;
        this.nClients = nClients;
        this.ending = ending;
        
        this.propertySearchInfoLanguageBox.setSelectedItem(language);
        
        if(this.client.getName().isEmpty())
        {
            this.propertySearchInfoMessageButton.setEnabled(false);
            this.propertySearchInfoMessageButton.setVisible(false);
            this.propertySearchInfoTicketButton.setEnabled(false);
            this.propertySearchInfoTicketButton.setVisible(false);
        }
        
        this.setInfo();
        this.changeButtons();
        this.changeTextToSelectedLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertySearchInfoPanel = new javax.swing.JPanel();
        propertySearchInfoTopBarPanel = new javax.swing.JPanel();
        propertySearchInfoLanguageBox = new javax.swing.JComboBox();
        propertySearchInfoNameLabel = new javax.swing.JLabel();
        propertySearchInfoMessageButton = new javax.swing.JButton();
        propertySearchInfoTicketButton = new javax.swing.JButton();
        propertySearchInfoRegisterButton = new javax.swing.JButton();
        propertySearchInfoLoginButton = new javax.swing.JButton();
        propertySearchInfoLogoPanel = new javax.swing.JPanel();
        propertySearchInfoInfoPanel = new javax.swing.JPanel();
        propertySearchInfoPropertyPanel = new javax.swing.JPanel();
        propertySearchInfoPhotoPanel = new javax.swing.JPanel();
        propertySearchInfoPhotoField = new javax.swing.JTextField();
        propertySearchInfoDescriptionPanel = new javax.swing.JPanel();
        propertySearchInfoDescriptionScrollPane = new javax.swing.JScrollPane();
        propertySearchInfoDescriptionArea = new javax.swing.JTextArea();
        propertySearchInfoPropertyNameField = new javax.swing.JTextField();
        propertySearchInfoPropertyInfoPanel = new javax.swing.JPanel();
        propertySearchInfoFinalPriceField = new javax.swing.JFormattedTextField();
        propertySearchInfoOwnerMessageButton = new javax.swing.JButton();
        propertySearchInfoPropertyTypeField = new javax.swing.JTextField();
        propertySearchInfoDiscountCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoDiscountLabel = new javax.swing.JLabel();
        propertySearchInfoOriginalPriceLabel = new javax.swing.JLabel();
        propertySearchInfoRatingField = new javax.swing.JTextField();
        propertySearchInfoExtrasBox = new javax.swing.JComboBox();
        propertySearchInfoExtrasDateField = new javax.swing.JTextField();
        propertySearchInfoCharacteristicsPanel = new javax.swing.JPanel();
        propertySearchInfoContainerPanel = new javax.swing.JPanel();
        propertySearchInfoMinClientsField = new javax.swing.JTextField();
        propertySearchInfoMaxClientsField = new javax.swing.JTextField();
        propertySearchInfoMinClientsLabel = new javax.swing.JLabel();
        propertySearchInfoMaxClientsLabel = new javax.swing.JLabel();
        propertySearchInfoNRoomsField = new javax.swing.JTextField();
        propertySearchInfoNBathroomsField = new javax.swing.JTextField();
        propertySearchInfoNRoomsLabel = new javax.swing.JLabel();
        propertySearchInfoNBathroomsLabel = new javax.swing.JLabel();
        propertySearchInfoNBedsField = new javax.swing.JTextField();
        propertySearchInfoBedsTypeBox = new javax.swing.JComboBox();
        propertySearchInfoNBedsLabel = new javax.swing.JLabel();
        propertySearchInfoExtrasLeftPanel = new javax.swing.JPanel();
        propertySearchInfoPetsCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoBreakfastCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoWifiCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoPoolCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoWashingMachineCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoKitchenCheckBox = new javax.swing.JCheckBox();
        propertySearchInfoRatingPanel = new javax.swing.JPanel();
        propertySearchInfoRatingScrollPane = new javax.swing.JScrollPane();
        propertySearchInfoRatingList = new javax.swing.JList();
        propertySearchInfoButtonPanel = new javax.swing.JPanel();
        propertySearchInfoBookingButton = new javax.swing.JButton();
        propertySearchInfoBackButton = new javax.swing.JButton();

        propertySearchInfoLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));
        propertySearchInfoLanguageBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                propertySearchInfoLanguageBoxPropertyChange(evt);
            }
        });

        propertySearchInfoNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        propertySearchInfoNameLabel.setText("Gustavo Moreira Vieira");
        propertySearchInfoNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertySearchInfoNameLabelMouseClicked(evt);
            }
        });

        propertySearchInfoMessageButton.setText("Mensagens");

        propertySearchInfoTicketButton.setText("Tickets");

        propertySearchInfoRegisterButton.setText("Registo");
        propertySearchInfoRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchInfoRegisterButtonActionPerformed(evt);
            }
        });

        propertySearchInfoLoginButton.setText("Login");
        propertySearchInfoLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchInfoLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propertySearchInfoTopBarPanelLayout = new javax.swing.GroupLayout(propertySearchInfoTopBarPanel);
        propertySearchInfoTopBarPanel.setLayout(propertySearchInfoTopBarPanelLayout);
        propertySearchInfoTopBarPanelLayout.setHorizontalGroup(
            propertySearchInfoTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propertySearchInfoLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoRegisterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoTicketButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoMessageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoNameLabel)
                .addContainerGap())
        );
        propertySearchInfoTopBarPanelLayout.setVerticalGroup(
            propertySearchInfoTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchInfoTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchInfoLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoNameLabel)
                    .addComponent(propertySearchInfoMessageButton)
                    .addComponent(propertySearchInfoTicketButton)
                    .addComponent(propertySearchInfoRegisterButton)
                    .addComponent(propertySearchInfoLoginButton))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout propertySearchInfoLogoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoLogoPanel);
        propertySearchInfoLogoPanel.setLayout(propertySearchInfoLogoPanelLayout);
        propertySearchInfoLogoPanelLayout.setHorizontalGroup(
            propertySearchInfoLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        propertySearchInfoLogoPanelLayout.setVerticalGroup(
            propertySearchInfoLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        propertySearchInfoPhotoField.setEditable(false);

        javax.swing.GroupLayout propertySearchInfoPhotoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoPhotoPanel);
        propertySearchInfoPhotoPanel.setLayout(propertySearchInfoPhotoPanelLayout);
        propertySearchInfoPhotoPanelLayout.setHorizontalGroup(
            propertySearchInfoPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoPhotoField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        propertySearchInfoPhotoPanelLayout.setVerticalGroup(
            propertySearchInfoPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoPhotoField)
                .addContainerGap())
        );

        propertySearchInfoDescriptionArea.setEditable(false);
        propertySearchInfoDescriptionArea.setColumns(20);
        propertySearchInfoDescriptionArea.setRows(5);
        propertySearchInfoDescriptionScrollPane.setViewportView(propertySearchInfoDescriptionArea);

        propertySearchInfoPropertyNameField.setEnabled(false);

        javax.swing.GroupLayout propertySearchInfoDescriptionPanelLayout = new javax.swing.GroupLayout(propertySearchInfoDescriptionPanel);
        propertySearchInfoDescriptionPanel.setLayout(propertySearchInfoDescriptionPanelLayout);
        propertySearchInfoDescriptionPanelLayout.setHorizontalGroup(
            propertySearchInfoDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoDescriptionPanelLayout.createSequentialGroup()
                .addGroup(propertySearchInfoDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchInfoDescriptionScrollPane)
                    .addComponent(propertySearchInfoPropertyNameField))
                .addContainerGap())
        );
        propertySearchInfoDescriptionPanelLayout.setVerticalGroup(
            propertySearchInfoDescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propertySearchInfoDescriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoPropertyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propertySearchInfoDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        propertySearchInfoFinalPriceField.setEditable(false);
        propertySearchInfoFinalPriceField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        propertySearchInfoFinalPriceField.setText("120,000.00€");
        propertySearchInfoFinalPriceField.setFocusable(false);

        propertySearchInfoOwnerMessageButton.setText("Enviar mensagem a DonoXPTO");

        propertySearchInfoPropertyTypeField.setEditable(false);
        propertySearchInfoPropertyTypeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoPropertyTypeField.setText("Quarto");

        propertySearchInfoDiscountCheckBox.setSelected(true);
        propertySearchInfoDiscountCheckBox.setText("Contém desconto");
        propertySearchInfoDiscountCheckBox.setEnabled(false);

        propertySearchInfoDiscountLabel.setForeground(new java.awt.Color(204, 51, 0));
        propertySearchInfoDiscountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        propertySearchInfoDiscountLabel.setText("(100%)");

        propertySearchInfoOriginalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        propertySearchInfoOriginalPriceLabel.setText("150,000.00€");

        propertySearchInfoRatingField.setEditable(false);
        propertySearchInfoRatingField.setBackground(new java.awt.Color(102, 153, 255));
        propertySearchInfoRatingField.setForeground(new java.awt.Color(255, 255, 255));
        propertySearchInfoRatingField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoRatingField.setText("7.9");
        propertySearchInfoRatingField.setToolTipText("Avaliação do Alojamento");
        propertySearchInfoRatingField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));

        javax.swing.GroupLayout propertySearchInfoPropertyInfoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoPropertyInfoPanel);
        propertySearchInfoPropertyInfoPanel.setLayout(propertySearchInfoPropertyInfoPanelLayout);
        propertySearchInfoPropertyInfoPanelLayout.setHorizontalGroup(
            propertySearchInfoPropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPropertyInfoPanelLayout.createSequentialGroup()
                .addGroup(propertySearchInfoPropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchInfoOwnerMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoDiscountCheckBox))
                .addGap(190, 190, 190)
                .addComponent(propertySearchInfoPropertyTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoRatingField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoPropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(propertySearchInfoPropertyInfoPanelLayout.createSequentialGroup()
                        .addComponent(propertySearchInfoOriginalPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchInfoDiscountLabel))
                    .addComponent(propertySearchInfoFinalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        propertySearchInfoPropertyInfoPanelLayout.setVerticalGroup(
            propertySearchInfoPropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPropertyInfoPanelLayout.createSequentialGroup()
                .addGroup(propertySearchInfoPropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchInfoFinalPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoOwnerMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoPropertyTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoRatingField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(propertySearchInfoPropertyInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchInfoDiscountCheckBox)
                    .addComponent(propertySearchInfoDiscountLabel)
                    .addComponent(propertySearchInfoOriginalPriceLabel))
                .addContainerGap())
        );

        propertySearchInfoExtrasBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contém Extras", "Extra 1", "Extra 2" }));

        propertySearchInfoExtrasDateField.setEditable(false);
        propertySearchInfoExtrasDateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoExtrasDateField.setText("17/06/2017");

        javax.swing.GroupLayout propertySearchInfoPropertyPanelLayout = new javax.swing.GroupLayout(propertySearchInfoPropertyPanel);
        propertySearchInfoPropertyPanel.setLayout(propertySearchInfoPropertyPanelLayout);
        propertySearchInfoPropertyPanelLayout.setHorizontalGroup(
            propertySearchInfoPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPropertyPanelLayout.createSequentialGroup()
                .addComponent(propertySearchInfoPhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchInfoDescriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoPropertyInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(propertySearchInfoPropertyPanelLayout.createSequentialGroup()
                        .addComponent(propertySearchInfoExtrasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchInfoExtrasDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        propertySearchInfoPropertyPanelLayout.setVerticalGroup(
            propertySearchInfoPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPropertyPanelLayout.createSequentialGroup()
                .addComponent(propertySearchInfoDescriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propertySearchInfoPropertyInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchInfoExtrasBox, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoExtrasDateField))
                .addContainerGap())
            .addComponent(propertySearchInfoPhotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        propertySearchInfoContainerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Extras"));

        propertySearchInfoMinClientsField.setEditable(false);
        propertySearchInfoMinClientsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoMinClientsField.setText("1");

        propertySearchInfoMaxClientsField.setEditable(false);
        propertySearchInfoMaxClientsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoMaxClientsField.setText("5");

        propertySearchInfoMinClientsLabel.setText("Nº Viajantes Mínimo");

        propertySearchInfoMaxClientsLabel.setText("Nº Viajantes Máximo");

        propertySearchInfoNRoomsField.setEditable(false);
        propertySearchInfoNRoomsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoNRoomsField.setText("3");

        propertySearchInfoNBathroomsField.setEditable(false);
        propertySearchInfoNBathroomsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoNBathroomsField.setText("7");

        propertySearchInfoNRoomsLabel.setText("Nº Quartos");

        propertySearchInfoNBathroomsLabel.setText("Nº Quartos de Banho");

        propertySearchInfoNBedsField.setEditable(false);
        propertySearchInfoNBedsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        propertySearchInfoNBedsField.setText("5");

        propertySearchInfoBedsTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipos de Cama" }));

        propertySearchInfoNBedsLabel.setText("Nº Camas");

        propertySearchInfoPetsCheckBox.setText("Animais de Estimação");
        propertySearchInfoPetsCheckBox.setEnabled(false);

        propertySearchInfoBreakfastCheckBox.setSelected(true);
        propertySearchInfoBreakfastCheckBox.setText("Pequeno Almoço");
        propertySearchInfoBreakfastCheckBox.setEnabled(false);

        propertySearchInfoWifiCheckBox.setText("Wi-fi");
        propertySearchInfoWifiCheckBox.setEnabled(false);

        javax.swing.GroupLayout propertySearchInfoExtrasLeftPanelLayout = new javax.swing.GroupLayout(propertySearchInfoExtrasLeftPanel);
        propertySearchInfoExtrasLeftPanel.setLayout(propertySearchInfoExtrasLeftPanelLayout);
        propertySearchInfoExtrasLeftPanelLayout.setHorizontalGroup(
            propertySearchInfoExtrasLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoExtrasLeftPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(propertySearchInfoExtrasLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchInfoPetsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoBreakfastCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoWifiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        propertySearchInfoExtrasLeftPanelLayout.setVerticalGroup(
            propertySearchInfoExtrasLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoExtrasLeftPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(propertySearchInfoPetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoBreakfastCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoWifiCheckBox)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        propertySearchInfoPoolCheckBox.setSelected(true);
        propertySearchInfoPoolCheckBox.setText("Piscina");
        propertySearchInfoPoolCheckBox.setEnabled(false);

        propertySearchInfoWashingMachineCheckBox.setText("Máquinha de Lavar");
        propertySearchInfoWashingMachineCheckBox.setEnabled(false);

        propertySearchInfoKitchenCheckBox.setText("Cozinha");
        propertySearchInfoKitchenCheckBox.setEnabled(false);

        javax.swing.GroupLayout propertySearchInfoContainerPanelLayout = new javax.swing.GroupLayout(propertySearchInfoContainerPanel);
        propertySearchInfoContainerPanel.setLayout(propertySearchInfoContainerPanelLayout);
        propertySearchInfoContainerPanelLayout.setHorizontalGroup(
            propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchInfoMinClientsField)
                    .addComponent(propertySearchInfoMaxClientsField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchInfoMinClientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoMaxClientsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchInfoNRoomsField)
                    .addComponent(propertySearchInfoNBathroomsField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(propertySearchInfoNRoomsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoNBathroomsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(propertySearchInfoContainerPanelLayout.createSequentialGroup()
                        .addComponent(propertySearchInfoNBedsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propertySearchInfoNBedsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(propertySearchInfoBedsTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(propertySearchInfoExtrasLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propertySearchInfoKitchenCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoWashingMachineCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertySearchInfoPoolCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        propertySearchInfoContainerPanelLayout.setVerticalGroup(
            propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchInfoMinClientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoMinClientsLabel)
                    .addComponent(propertySearchInfoNRoomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoNRoomsLabel)
                    .addComponent(propertySearchInfoNBedsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propertySearchInfoNBedsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propertySearchInfoContainerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(propertySearchInfoContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(propertySearchInfoMaxClientsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(propertySearchInfoMaxClientsLabel)
                            .addComponent(propertySearchInfoNBathroomsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(propertySearchInfoNBathroomsLabel)))
                    .addComponent(propertySearchInfoBedsTypeBox))
                .addGap(51, 51, 51))
            .addGroup(propertySearchInfoContainerPanelLayout.createSequentialGroup()
                .addComponent(propertySearchInfoExtrasLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(propertySearchInfoContainerPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(propertySearchInfoKitchenCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoWashingMachineCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoPoolCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout propertySearchInfoCharacteristicsPanelLayout = new javax.swing.GroupLayout(propertySearchInfoCharacteristicsPanel);
        propertySearchInfoCharacteristicsPanel.setLayout(propertySearchInfoCharacteristicsPanelLayout);
        propertySearchInfoCharacteristicsPanelLayout.setHorizontalGroup(
            propertySearchInfoCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoCharacteristicsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        propertySearchInfoCharacteristicsPanelLayout.setVerticalGroup(
            propertySearchInfoCharacteristicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoCharacteristicsPanelLayout.createSequentialGroup()
                .addComponent(propertySearchInfoContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        propertySearchInfoRatingList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        propertySearchInfoRatingScrollPane.setViewportView(propertySearchInfoRatingList);

        propertySearchInfoBookingButton.setText("Reservar");
        propertySearchInfoBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchInfoBookingButtonActionPerformed(evt);
            }
        });

        propertySearchInfoBackButton.setText("Voltar");
        propertySearchInfoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertySearchInfoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout propertySearchInfoButtonPanelLayout = new javax.swing.GroupLayout(propertySearchInfoButtonPanel);
        propertySearchInfoButtonPanel.setLayout(propertySearchInfoButtonPanelLayout);
        propertySearchInfoButtonPanelLayout.setHorizontalGroup(
            propertySearchInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propertySearchInfoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        propertySearchInfoButtonPanelLayout.setVerticalGroup(
            propertySearchInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propertySearchInfoButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(propertySearchInfoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertySearchInfoBookingButton)
                    .addComponent(propertySearchInfoBackButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout propertySearchInfoRatingPanelLayout = new javax.swing.GroupLayout(propertySearchInfoRatingPanel);
        propertySearchInfoRatingPanel.setLayout(propertySearchInfoRatingPanelLayout);
        propertySearchInfoRatingPanelLayout.setHorizontalGroup(
            propertySearchInfoRatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoRatingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoRatingScrollPane)
                .addContainerGap())
            .addComponent(propertySearchInfoButtonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        propertySearchInfoRatingPanelLayout.setVerticalGroup(
            propertySearchInfoRatingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoRatingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(propertySearchInfoRatingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(propertySearchInfoButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout propertySearchInfoInfoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoInfoPanel);
        propertySearchInfoInfoPanel.setLayout(propertySearchInfoInfoPanelLayout);
        propertySearchInfoInfoPanelLayout.setHorizontalGroup(
            propertySearchInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchInfoPropertyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchInfoCharacteristicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchInfoRatingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        propertySearchInfoInfoPanelLayout.setVerticalGroup(
            propertySearchInfoInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoInfoPanelLayout.createSequentialGroup()
                .addComponent(propertySearchInfoPropertyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoCharacteristicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoRatingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout propertySearchInfoPanelLayout = new javax.swing.GroupLayout(propertySearchInfoPanel);
        propertySearchInfoPanel.setLayout(propertySearchInfoPanelLayout);
        propertySearchInfoPanelLayout.setHorizontalGroup(
            propertySearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchInfoTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchInfoLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(propertySearchInfoInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        propertySearchInfoPanelLayout.setVerticalGroup(
            propertySearchInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propertySearchInfoPanelLayout.createSequentialGroup()
                .addComponent(propertySearchInfoTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propertySearchInfoInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertySearchInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void propertySearchInfoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchInfoBackButtonActionPerformed
        // TODO add your handling code here:
        this.jpps = new JPPropertySearch(this.frame, this.client, this.map, this.county, this.propertyType, this.nClients, this.starting, this.ending, this.propertySearchInfoLanguageBox.getSelectedItem());
        frame.changePanel(this.jpps);
    }//GEN-LAST:event_propertySearchInfoBackButtonActionPerformed

    private void propertySearchInfoBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchInfoBookingButtonActionPerformed
        // TODO add your handling code here:
        this.jpb = new JPBooking(this.frame, this.client, this.map, this.p, this.county, this.propertyType, this.nClients, this.starting, this.ending, this.propertySearchInfoLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpb);
    }//GEN-LAST:event_propertySearchInfoBookingButtonActionPerformed

    private void propertySearchInfoLanguageBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_propertySearchInfoLanguageBoxPropertyChange
        // TODO add your handling code here:
        this.changeTextToSelectedLanguage();
    }//GEN-LAST:event_propertySearchInfoLanguageBoxPropertyChange

    private void propertySearchInfoRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchInfoRegisterButtonActionPerformed
        // TODO add your handling code here:
        Application a = new Application();
        
        a.jpr = new JPRegister(a, this.propertySearchInfoLanguageBox.getSelectedItem());
        a.changePanel(a.jpr);
        
        Thread t = new Thread(a);
        t.start();
        
        this.frame.threadCounter++;
    }//GEN-LAST:event_propertySearchInfoRegisterButtonActionPerformed

    private void propertySearchInfoLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertySearchInfoLoginButtonActionPerformed
        // TODO add your handling code here:
        Application a = new Application();
        
        a.jpl = new JPLogin(a, this.propertySearchInfoLanguageBox.getSelectedItem());
        a.changePanel(a.jpl);
        
        Thread t = new Thread(a);
        t.start();
        
        this.frame.threadCounter++;
    }//GEN-LAST:event_propertySearchInfoLoginButtonActionPerformed

    private void propertySearchInfoNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertySearchInfoNameLabelMouseClicked
        // TODO add your handling code here:
        
        this.jpp = new JPProfile(this.frame, this.client, this.propertySearchInfoLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jpp);
    }//GEN-LAST:event_propertySearchInfoNameLabelMouseClicked

    private void setInfo() {
        this.propertySearchInfoNameLabel.setText(this.client.getName());
        this.propertySearchInfoPropertyNameField.setText(this.p.getName());
        this.propertySearchInfoDescriptionArea.setText(this.p.getDescription());
        
        if(this.propertySearchInfoLanguageBox.getSelectedIndex() == 0)
        {
            this.propertySearchInfoOwnerMessageButton.setText("Enviar mensagem a " + this.p.getOwner().getName());
        }
        else
        {
            this.propertySearchInfoOwnerMessageButton.setText("Send a message to " + this.p.getOwner().getName());
        }
            
        this.propertySearchInfoPropertyTypeField.setText(this.p.getPropertyType().getName());
        this.propertySearchInfoRatingField.setText(String.valueOf(this.p.getPropertyRatingMedianPoints()));
        double calc = this.p.getPricePerNight() * (1 - ((double)this.p.getDiscount().getPercentage()/100));
        this.propertySearchInfoFinalPriceField.setText(String.valueOf(calc));
        
        if(this.p.getDiscount().getPercentage() == 0)
        {
            this.propertySearchInfoDiscountLabel.setEnabled(false);
            this.propertySearchInfoDiscountLabel.setVisible(false);
            this.propertySearchInfoOriginalPriceLabel.setEnabled(false);
            this.propertySearchInfoOriginalPriceLabel.setVisible(false);
            this.propertySearchInfoDiscountCheckBox.setSelected(false);
        }
        else
        {
            this.propertySearchInfoDiscountLabel.setText(String.valueOf(this.p.getDiscount().getPercentage()) + "%");
            this.propertySearchInfoOriginalPriceLabel.setText(String.valueOf(this.p.getPricePerNight()));
            this.propertySearchInfoDiscountCheckBox.setSelected(true);
        }
        
        this.propertySearchInfoMinClientsField.setText(String.valueOf(this.p.getCharacteristics().getMinClients()));
        this.propertySearchInfoMaxClientsField.setText(String.valueOf(this.p.getCharacteristics().getMaxClients()));
        this.propertySearchInfoNRoomsField.setText(String.valueOf(this.p.getCharacteristics().getRoomsQuantity()));
        this.propertySearchInfoNBathroomsField.setText(String.valueOf(this.p.getCharacteristics().getBathroomQuantity()));
        this.propertySearchInfoNBedsField.setText(String.valueOf(Repository.getRepo().nBeds(p)));
        
        this.propertySearchInfoPetsCheckBox.setSelected(this.p.getCharacteristics().isPets());
        this.propertySearchInfoBreakfastCheckBox.setSelected(this.p.getCharacteristics().isBreakfast());
        this.propertySearchInfoWifiCheckBox.setSelected(this.p.getCharacteristics().isWifi());
        this.propertySearchInfoKitchenCheckBox.setSelected(this.p.getCharacteristics().isKitchen());
        this.propertySearchInfoWashingMachineCheckBox.setSelected(this.p.getCharacteristics().isWashingMachine());
        this.propertySearchInfoPoolCheckBox.setSelected(this.p.getCharacteristics().isPool());
        this.propertySearchInfoBedsTypeBox.setModel(new DefaultComboBoxModel(this.p.getCharacteristics().getBedTypeList().toArray()));
        
        if(this.p.getExtras().isEmpty())
        {
            this.propertySearchInfoExtrasBox.setEnabled(false);
            this.propertySearchInfoExtrasBox.setVisible(false);
            this.propertySearchInfoExtrasDateField.setEnabled(false);
            this.propertySearchInfoExtrasDateField.setVisible(false);
        }
        else
        {
            this.propertySearchInfoExtrasBox.setModel(new DefaultComboBoxModel(this.p.getExtras().toArray()));
            this.propertySearchInfoExtrasDateField.setText(String.valueOf(this.p.getExtras().get(this.propertySearchInfoExtrasBox.getSelectedIndex()).getEndingDate()));
        }
        
        //this.propertySearchInfoRatingList.setModel(this.p.getRatings().toArray());
    }
    
    private void changeButtons() {
        if(this.client.getName().isEmpty())
        {
            this.propertySearchInfoNameLabel.setEnabled(false);
            this.propertySearchInfoNameLabel.setVisible(false);
            this.propertySearchInfoMessageButton.setEnabled(false);
            this.propertySearchInfoMessageButton.setVisible(false);
            this.propertySearchInfoTicketButton.setEnabled(false);
            this.propertySearchInfoTicketButton.setVisible(false);
            this.propertySearchInfoOwnerMessageButton.setEnabled(false);
            this.propertySearchInfoBookingButton.setEnabled(false);
        }
        else
        {
            this.propertySearchInfoLoginButton.setEnabled(false);
            this.propertySearchInfoLoginButton.setVisible(false);
            this.propertySearchInfoRegisterButton.setEnabled(false);
            this.propertySearchInfoRegisterButton.setVisible(false);
        }
    }
    
    private void changeTextToSelectedLanguage() {
        
        if(this.propertySearchInfoLanguageBox.getSelectedIndex() == 0)
        {
            this.propertySearchInfoDiscountCheckBox.setText("Contém desconto");
            this.propertySearchInfoMinClientsLabel.setText("Nº Viajantes Mínimo");
            this.propertySearchInfoMaxClientsLabel.setText("Nº Viajantes Máximo");
            this.propertySearchInfoNRoomsLabel.setText("Nº Quartos");
            this.propertySearchInfoNBathroomsLabel.setText("Nº Quartos de Banho");
            this.propertySearchInfoPetsCheckBox.setText("Animais de Estimação");
            this.propertySearchInfoBreakfastCheckBox.setText("Pequeno Almoço");
            this.propertySearchInfoKitchenCheckBox.setText("Cozinha");
            this.propertySearchInfoWashingMachineCheckBox.setText("Máquina de Lavar");
            this.propertySearchInfoPoolCheckBox.setText("Piscina");
        }
        else
        {
            this.propertySearchInfoDiscountCheckBox.setText("Contains discount");
            this.propertySearchInfoMinClientsLabel.setText("Minimum Travelers");
            this.propertySearchInfoMaxClientsLabel.setText("Maximum Travelers");
            this.propertySearchInfoNRoomsLabel.setText("Nº Rooms");
            this.propertySearchInfoNBathroomsLabel.setText("Nº Bathrooms");
            this.propertySearchInfoPetsCheckBox.setText("Pets");
            this.propertySearchInfoBreakfastCheckBox.setText("Breakfast");
            this.propertySearchInfoKitchenCheckBox.setText("Kitchen");
            this.propertySearchInfoWashingMachineCheckBox.setText("Washing Machine");
            this.propertySearchInfoPoolCheckBox.setText("Pool");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton propertySearchInfoBackButton;
    private javax.swing.JComboBox propertySearchInfoBedsTypeBox;
    private javax.swing.JButton propertySearchInfoBookingButton;
    private javax.swing.JCheckBox propertySearchInfoBreakfastCheckBox;
    private javax.swing.JPanel propertySearchInfoButtonPanel;
    private javax.swing.JPanel propertySearchInfoCharacteristicsPanel;
    private javax.swing.JPanel propertySearchInfoContainerPanel;
    private javax.swing.JTextArea propertySearchInfoDescriptionArea;
    private javax.swing.JPanel propertySearchInfoDescriptionPanel;
    private javax.swing.JScrollPane propertySearchInfoDescriptionScrollPane;
    private javax.swing.JCheckBox propertySearchInfoDiscountCheckBox;
    private javax.swing.JLabel propertySearchInfoDiscountLabel;
    private javax.swing.JComboBox propertySearchInfoExtrasBox;
    private javax.swing.JTextField propertySearchInfoExtrasDateField;
    private javax.swing.JPanel propertySearchInfoExtrasLeftPanel;
    private javax.swing.JFormattedTextField propertySearchInfoFinalPriceField;
    private javax.swing.JPanel propertySearchInfoInfoPanel;
    private javax.swing.JCheckBox propertySearchInfoKitchenCheckBox;
    private javax.swing.JComboBox propertySearchInfoLanguageBox;
    private javax.swing.JButton propertySearchInfoLoginButton;
    private javax.swing.JPanel propertySearchInfoLogoPanel;
    private javax.swing.JTextField propertySearchInfoMaxClientsField;
    private javax.swing.JLabel propertySearchInfoMaxClientsLabel;
    private javax.swing.JButton propertySearchInfoMessageButton;
    private javax.swing.JTextField propertySearchInfoMinClientsField;
    private javax.swing.JLabel propertySearchInfoMinClientsLabel;
    private javax.swing.JTextField propertySearchInfoNBathroomsField;
    private javax.swing.JLabel propertySearchInfoNBathroomsLabel;
    private javax.swing.JTextField propertySearchInfoNBedsField;
    private javax.swing.JLabel propertySearchInfoNBedsLabel;
    private javax.swing.JTextField propertySearchInfoNRoomsField;
    private javax.swing.JLabel propertySearchInfoNRoomsLabel;
    private javax.swing.JLabel propertySearchInfoNameLabel;
    private javax.swing.JLabel propertySearchInfoOriginalPriceLabel;
    private javax.swing.JButton propertySearchInfoOwnerMessageButton;
    private javax.swing.JPanel propertySearchInfoPanel;
    private javax.swing.JCheckBox propertySearchInfoPetsCheckBox;
    private javax.swing.JTextField propertySearchInfoPhotoField;
    private javax.swing.JPanel propertySearchInfoPhotoPanel;
    private javax.swing.JCheckBox propertySearchInfoPoolCheckBox;
    private javax.swing.JPanel propertySearchInfoPropertyInfoPanel;
    private javax.swing.JTextField propertySearchInfoPropertyNameField;
    private javax.swing.JPanel propertySearchInfoPropertyPanel;
    private javax.swing.JTextField propertySearchInfoPropertyTypeField;
    private javax.swing.JTextField propertySearchInfoRatingField;
    private javax.swing.JList propertySearchInfoRatingList;
    private javax.swing.JPanel propertySearchInfoRatingPanel;
    private javax.swing.JScrollPane propertySearchInfoRatingScrollPane;
    private javax.swing.JButton propertySearchInfoRegisterButton;
    private javax.swing.JButton propertySearchInfoTicketButton;
    private javax.swing.JPanel propertySearchInfoTopBarPanel;
    private javax.swing.JCheckBox propertySearchInfoWashingMachineCheckBox;
    private javax.swing.JCheckBox propertySearchInfoWifiCheckBox;
    // End of variables declaration//GEN-END:variables
}
