/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

import projectoalojamento.Repository;

/**
 *
 * @author Gustavo Vieira
 */
public class JPRating extends javax.swing.JPanel {

    private Application frame;
    private JPBookingList jbrl;
    private Repository repo;
    
    /**
     * Creates new form JPRating
     */
    public JPRating(Application frame, Repository repo, Object language) {
        initComponents();
        this.frame = frame;
        this.ratingLanguageBox.setSelectedItem(language);
        this.repo=repo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingPanel = new javax.swing.JPanel();
        ratingTopBarPanel = new javax.swing.JPanel();
        ratingLanguageBox = new javax.swing.JComboBox();
        ratingNameLabel = new javax.swing.JLabel();
        ratingLogoPanel = new javax.swing.JPanel();
        ratingInfoPanel = new javax.swing.JPanel();
        ratingTitleField = new javax.swing.JTextField();
        ratingNClientsSpinner = new javax.swing.JSpinner();
        ratingMessageScrollPane = new javax.swing.JScrollPane();
        ratingMessageArea = new javax.swing.JTextArea();
        ratingButtonInfoPanel = new javax.swing.JPanel();
        ratingOwnerField = new javax.swing.JTextField();
        ratingNDaysField = new javax.swing.JTextField();
        ratingButton = new javax.swing.JButton();
        ratingBackButton = new javax.swing.JButton();

        ratingLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));

        ratingNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ratingNameLabel.setText("Gustavo Moreira Vieira");

        javax.swing.GroupLayout ratingTopBarPanelLayout = new javax.swing.GroupLayout(ratingTopBarPanel);
        ratingTopBarPanel.setLayout(ratingTopBarPanelLayout);
        ratingTopBarPanelLayout.setHorizontalGroup(
            ratingTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ratingLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ratingNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ratingTopBarPanelLayout.setVerticalGroup(
            ratingTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratingTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratingNameLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ratingLogoPanelLayout = new javax.swing.GroupLayout(ratingLogoPanel);
        ratingLogoPanel.setLayout(ratingLogoPanelLayout);
        ratingLogoPanelLayout.setHorizontalGroup(
            ratingLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ratingLogoPanelLayout.setVerticalGroup(
            ratingLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        ratingTitleField.setText(" Título");

        ratingNClientsSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(1.0f)));
        ratingNClientsSpinner.setToolTipText("Pontos de avaliação");
        ratingNClientsSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        ratingMessageArea.setColumns(20);
        ratingMessageArea.setRows(5);
        ratingMessageArea.setText("Mensagem de avaliação");
        ratingMessageScrollPane.setViewportView(ratingMessageArea);

        ratingOwnerField.setEditable(false);
        ratingOwnerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ratingOwnerField.setText("DonoXPTO");

        ratingNDaysField.setEditable(false);
        ratingNDaysField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ratingNDaysField.setText("5 Dias");

        ratingButton.setText("Voltar");
        ratingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingButtonActionPerformed(evt);
            }
        });

        ratingBackButton.setText("Avaliar");
        ratingBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ratingButtonInfoPanelLayout = new javax.swing.GroupLayout(ratingButtonInfoPanel);
        ratingButtonInfoPanel.setLayout(ratingButtonInfoPanelLayout);
        ratingButtonInfoPanelLayout.setHorizontalGroup(
            ratingButtonInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingButtonInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ratingOwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingNDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ratingBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingButton)
                .addContainerGap())
        );
        ratingButtonInfoPanelLayout.setVerticalGroup(
            ratingButtonInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ratingButtonInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ratingButtonInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ratingOwnerField)
                    .addComponent(ratingNDaysField)
                    .addComponent(ratingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(ratingBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout ratingInfoPanelLayout = new javax.swing.GroupLayout(ratingInfoPanel);
        ratingInfoPanel.setLayout(ratingInfoPanelLayout);
        ratingInfoPanelLayout.setHorizontalGroup(
            ratingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingMessageScrollPane)
                    .addGroup(ratingInfoPanelLayout.createSequentialGroup()
                        .addComponent(ratingTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ratingNClientsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(ratingButtonInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ratingInfoPanelLayout.setVerticalGroup(
            ratingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ratingInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ratingNClientsSpinner)
                    .addComponent(ratingTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingMessageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ratingButtonInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ratingPanelLayout = new javax.swing.GroupLayout(ratingPanel);
        ratingPanel.setLayout(ratingPanelLayout);
        ratingPanelLayout.setHorizontalGroup(
            ratingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratingTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ratingLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ratingInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ratingPanelLayout.setVerticalGroup(
            ratingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingPanelLayout.createSequentialGroup()
                .addComponent(ratingTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratingInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ratingBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingBackButtonActionPerformed
        // TODO add your handling code here:
        this.jbrl = new JPBookingList(this.frame, this.repo,this.ratingLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jbrl);
    }//GEN-LAST:event_ratingBackButtonActionPerformed

    private void ratingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingButtonActionPerformed
        // TODO add your handling code here:
        this.jbrl = new JPBookingList(this.frame, this.repo,this.ratingLanguageBox.getSelectedItem());
        this.frame.changePanel(this.jbrl);
    }//GEN-LAST:event_ratingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ratingBackButton;
    private javax.swing.JButton ratingButton;
    private javax.swing.JPanel ratingButtonInfoPanel;
    private javax.swing.JPanel ratingInfoPanel;
    private javax.swing.JComboBox ratingLanguageBox;
    private javax.swing.JPanel ratingLogoPanel;
    private javax.swing.JTextArea ratingMessageArea;
    private javax.swing.JScrollPane ratingMessageScrollPane;
    private javax.swing.JSpinner ratingNClientsSpinner;
    private javax.swing.JTextField ratingNDaysField;
    private javax.swing.JLabel ratingNameLabel;
    private javax.swing.JTextField ratingOwnerField;
    private javax.swing.JPanel ratingPanel;
    private javax.swing.JTextField ratingTitleField;
    private javax.swing.JPanel ratingTopBarPanel;
    // End of variables declaration//GEN-END:variables
}
