/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento.application;

/**
 *
 * @author Gustavo Vieira
 */
public class JPTicket extends javax.swing.JPanel {

    /**
     * Creates new form JPTicket
     */
    public JPTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketPanel = new javax.swing.JPanel();
        ticketTopBarPanel = new javax.swing.JPanel();
        ticketLanguageBox = new javax.swing.JComboBox();
        ticketNameLabel = new javax.swing.JLabel();
        ticketLogoPanel = new javax.swing.JPanel();
        ticketInfoPanel = new javax.swing.JPanel();
        ticketTypeBox = new javax.swing.JComboBox();
        ticketSubjectField = new javax.swing.JTextField();
        ticketMessageScrollPane = new javax.swing.JScrollPane();
        ticketMessageArea = new javax.swing.JTextArea();
        ticketButtonPanel = new javax.swing.JPanel();
        ticketSendButton = new javax.swing.JButton();
        ticketBackButton = new javax.swing.JButton();

        ticketLanguageBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PT", "EN" }));

        ticketNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ticketNameLabel.setText("Gustavo Moreira Vieira");

        javax.swing.GroupLayout ticketTopBarPanelLayout = new javax.swing.GroupLayout(ticketTopBarPanel);
        ticketTopBarPanel.setLayout(ticketTopBarPanelLayout);
        ticketTopBarPanelLayout.setHorizontalGroup(
            ticketTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(ticketNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ticketTopBarPanelLayout.setVerticalGroup(
            ticketTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketTopBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticketTopBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketLanguageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketNameLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ticketLogoPanelLayout = new javax.swing.GroupLayout(ticketLogoPanel);
        ticketLogoPanel.setLayout(ticketLogoPanelLayout);
        ticketLogoPanelLayout.setHorizontalGroup(
            ticketLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ticketLogoPanelLayout.setVerticalGroup(
            ticketLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        ticketTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Problemas com a conta", "Problemas com as reservas" }));

        ticketSubjectField.setText(" Assunto: ");

        ticketMessageArea.setColumns(20);
        ticketMessageArea.setRows(5);
        ticketMessageArea.setText(" Escreva aqui o seu problema...");
        ticketMessageScrollPane.setViewportView(ticketMessageArea);

        ticketSendButton.setText("Enviar");

        ticketBackButton.setText("Voltar");

        javax.swing.GroupLayout ticketButtonPanelLayout = new javax.swing.GroupLayout(ticketButtonPanel);
        ticketButtonPanel.setLayout(ticketButtonPanelLayout);
        ticketButtonPanelLayout.setHorizontalGroup(
            ticketButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketSendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ticketBackButton)
                .addContainerGap())
        );
        ticketButtonPanelLayout.setVerticalGroup(
            ticketButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ticketButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketSendButton)
                    .addComponent(ticketBackButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout ticketInfoPanelLayout = new javax.swing.GroupLayout(ticketInfoPanel);
        ticketInfoPanel.setLayout(ticketInfoPanelLayout);
        ticketInfoPanelLayout.setHorizontalGroup(
            ticketInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ticketInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ticketMessageScrollPane)
                    .addComponent(ticketSubjectField)
                    .addComponent(ticketTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(ticketButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ticketInfoPanelLayout.setVerticalGroup(
            ticketInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketSubjectField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketMessageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ticketButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ticketPanelLayout = new javax.swing.GroupLayout(ticketPanel);
        ticketPanel.setLayout(ticketPanelLayout);
        ticketPanelLayout.setHorizontalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketTopBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ticketLogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ticketInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ticketPanelLayout.setVerticalGroup(
            ticketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketPanelLayout.createSequentialGroup()
                .addComponent(ticketTopBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ticketBackButton;
    private javax.swing.JPanel ticketButtonPanel;
    private javax.swing.JPanel ticketInfoPanel;
    private javax.swing.JComboBox ticketLanguageBox;
    private javax.swing.JPanel ticketLogoPanel;
    private javax.swing.JTextArea ticketMessageArea;
    private javax.swing.JScrollPane ticketMessageScrollPane;
    private javax.swing.JLabel ticketNameLabel;
    private javax.swing.JPanel ticketPanel;
    private javax.swing.JButton ticketSendButton;
    private javax.swing.JTextField ticketSubjectField;
    private javax.swing.JPanel ticketTopBarPanel;
    private javax.swing.JComboBox ticketTypeBox;
    // End of variables declaration//GEN-END:variables
}
