/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoalojamento;

import javax.swing.*;
import java.awt.event.*;
import java.util.List;
import user.User;

/**
 *
 * @author Gustavo Vieira
 */
public class Application3 extends javax.swing.JFrame {

    static JFrame j;
    static JComboBox favoriteShows;
    static JButton button1;
    static String infoOnComponent = "";
    /**
     * Creates new form Application3
     */
    public Application3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application3().setVisible(true);
            }
        });
        
        j = new JFrame();
        
        j.setSize(400,400);
        j.setLocationRelativeTo(null);
        j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        j.setTitle("My Fourth Frame");
        
        JPanel thePanel = new JPanel();
        
        String[] shows = {"Breaking Bad", "Life on Mars", "Doctor Who"};
        favoriteShows = new JComboBox(shows);
        favoriteShows.addItem("Pushing Daisies");
        
        thePanel.add(favoriteShows);
        
        button1 = new JButton("Get Answer");
        
        ListenForButtons lForButton = new ListenForButtons();
        button1.addActionListener(lForButton);
        thePanel.add(button1);
        
        j.add(thePanel);
        j.setVisible(true);
        
        favoriteShows.insertItemAt("Dexter", 1); // Dexter no index 1
        favoriteShows.setMaximumRowCount(3); // Nº max linhas mostradas
        favoriteShows.removeItem("Dexter"); // remove dexter
        favoriteShows.removeItemAt(1); // remove index 1
    }
    
    private static class ListenForButtons implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource() == button1) {
                favoriteShows.setEditable(true); // editável a combo box
                infoOnComponent += "Item at 0: " + favoriteShows.getItemAt(0) + "\n";
                infoOnComponent += "Num of Shows: " + favoriteShows.getItemCount() + "\n";
                infoOnComponent += "Selected ID: " + favoriteShows.getSelectedIndex() + "\n";
                infoOnComponent += "Selected Value: " + favoriteShows.getSelectedItem() + "\n";
                infoOnComponent += "Are Editable: " + favoriteShows.isEditable() + "\n";
                
                JOptionPane.showMessageDialog(Application3.j, infoOnComponent, "Information", JOptionPane.INFORMATION_MESSAGE);
                
                infoOnComponent = "";
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
